### ISSUE TITLE
Issue with Souliss binding

### ISSUE THREAD

**Issue by fhempeter** [openhab/openhab1-addons#3028]
Dear colleagues,

using openhab 1.7.1 latest build (download last week).

When using the Souliss binding example from https://github.com/openhab/openhab/wiki/Souliss-Arduino-based-SmartHome-Binding, the connection to the Souliss gateway does not establish.

In the log I see the following error entries that seem relevant:
2015-08-06 19:48:30.877 [ERROR] [b.s.internal.SysteminfoBinding] - System monitor error: {}
org.hyperic.sigar.SigarException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getNetInterfaceList()[Ljava/lang/String;
        at org.hyperic.sigar.SigarProxyCache.invoke(SigarProxyCache.java:220) ~[sigar-1.6.4.jar:na]
        at com.sun.proxy.$Proxy72.getNetInterfaceList(Unknown Source) ~[na:na]
        at org.openhab.binding.systeminfo.internal.SysteminfoBinding.initializeSystemMonitor(SysteminfoBinding.java:419) [bundlefile:na]
        at org.openhab.binding.systeminfo.internal.SysteminfoBinding.updated(SysteminfoBinding.java:403) [bundlefile:na]
        at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]

2015-08-06 19:48:32.580 [INFO ] [.o.b.s.internal.SoulissBinding] - PARAMETER: REFRESH_DBSTRUCT_TIME = 600000 souliss:REFRESH_SUBSCRIPTION_TIME=120000 soulis$
2015-08-06 19:48:32.607 [ERROR] [.service.AbstractActiveService] - Error while executing background thread Souliss Refresh Service
java.lang.NullPointerException: null
        at org.openhab.binding.souliss.internal.SoulissBinding.execute(SoulissBinding.java:343) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]

Configuration files just like on the example, but just in case here are the relevant sections:
opehab.cfg:
souliss:IP_LAN=192.168.181.77
souliss:USER_INDEX=72  
souliss:NODE_INDEX=133
# SERVERPORT - Leave empty for casual port

souliss:SERVERPORT=
# time in mills souliss:

souliss:REFRESH_DBSTRUCT_TIME=600000 souliss:REFRESH_SUBSCRIPTION_TIME=120000 souliss:REFRESH_HEALTY_TIME=60000 souliss:REFRESH_MONITOR_TIME=500 souliss:SEND_DELAY=1500 souliss:SEND_MIN_DELAY=100 souliss:SECURE_SEND_TIMEOUT_TO_REQUEUE=5000 souliss:SECURE_SEND_TIMEOUT_TO_REMOVE_PACKET=30000

items.default:
Group All
Group grp1 (All)
Group Diagnostic (All)
Group TechnicView_Node0 (All)
Switch SimpleLight "SimpleLight" (grp1, TechnicView_Node0) {souliss="T11:0:0", autoupdate="true"}
Number HEALTHNodo0 "Health Node 0 [%1d]" <keyring> (Diagnostic, TechnicView_Node0, Health) {souliss="D98:0:998"}
String TIMESTAMP_Nodo0 "Update Node 0 [%1$td.%1$tm.%1$tY %1$tk:%1$tM:%1$tS]" <keyring> (Diagnostic, TechnicView_Node0) {souliss="D99:0:999"}

Thank you !

Peter
##

**Comment by 9037568** [comment]
@fhempeter is this still occurring in 1.8.3 or the latest snapshot? If so, please attach a debug log.
