### ISSUE TITLE
MQTT binding: changing protocol requires openhab restart

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab1-addons#3394]
When I changed my MQTT installation from "tcp" to "ssl" on openhab.cfg, I experienced the following error: The binding did not connect to mosquitto, and openhab.log showed an exception:

``` java
21:32:59.155 INFO  o.o.i.t.m.i.MqttBrokerConnection[:114]- Starting MQTT broker connection 'home'
21:32:59.165 ERROR o.o.i.t.mqtt.MqttService[:114]- Error starting broker connection
org.eclipse.paho.client.mqttv3.MqttException: The specified SocketFactory type does not match the broker URI
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:27)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.createNetworkModule(MqttAsyncClient.java:355)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.createNetworkModules(MqttAsyncClient.java:318)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:475)
        at org.eclipse.paho.client.mqttv3.MqttClient.connect(MqttClient.java:236)
        at org.openhab.io.transport.mqtt.internal.MqttBrokerConnection.openConnection(MqttBrokerConnection.java:354)
21:33:30.605 INFO  o.o.i.t.m.i.MqttBrokerConnection[:114]- Starting MQTT broker connection 'home'
21:34:30.605 INFO  o.o.i.t.m.i.MqttBrokerConnection[:114]- Starting MQTT broker connection 'home'
...
```

However, after a restart of Openhab, it worked fine.

Thus, I assume some problem in the code which handles config refresh in for the binding. I already looked at the code, but I could not identify the problem so far. MqttBrokerConnection:openConnection() from MqttBrokerConnection.java is called, and it decides which SocketFactory to use based on the "ssl" in the url.
I noticed two possible issues:
- url.toLowerCase().contains("ssl") should be changed to url.toLowerCase().startsWith("ssl") to allow host names containing the string "ssl"
- the dictionary brokerConnections is not cleared at the beginning of MqttService:updated() in MqttService.java, maybe it is a good idea to do so. This could solve the problem....

My setup: openhab core 1.7.0-rc1, addons 1.7.1.
##

**Comment by 9037568** [comment]
I think the changes being worked for #5500 will also resolve this issue. Stay tuned...
