### ISSUE TITLE
XBMC Binding: Player.GetItems stop, playpause errors in log

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab1-addons#3495]
I've just configured the xbmc binding and now I get a lot of these errors in the log:

`Error handling POST response from XBMC
org.openhab.binding.xbmc.rpc.RpcCall$RpcException: {code=-32602, data={method=Player.GetItem, stack={message=array element at index 0 does not match, name=Item.Fields.Base, property={message=Received value does not match any of the defined enum values, type=string}, type=array}}, message=Invalid params.}`

I inserted a debug log and found out that this json request is sent:

`{"id":"61d0630e-d59d-4a77-b380-84fda4fb6744","method":"Player.GetItem","params":{"playerid":1,"properties":["stop","playpause"]},"jsonrpc":"2.0"}`

But the properties "stop" and "playpause" cannot be retreived using "Player.GetItems". Please fix this.
##

**Comment by Dom1n1c** [comment]
I can confirm,that there are multiple errors with the XBMC (Kodi) Binding.
(Will it be renamed to Kodi soon?)
The Xbmc Binding shows, that Kodi is offline. But that isn't correct.

`2016-05-15 16:38:22.540 [WARN ] [b.x.internal.XbmcActiveBinding] - Received command (Szene "Fernsehen" aktiviert.) for item KodiLiving_Notification but the connection to the XBMC instance #Livingroom is down, ignoring`

`2016-05-15 16:40:25.888 [WARN ] [b.x.internal.XbmcActiveBinding] - Received update (100) for item KodiLiving_Volume but the connection to the XBMC instance #Livingroom is down, ignoring`

Also i can not get the current Name of a TV Station.
The Bug seems to affect multiple users: [http://ci8.de/kodiopenhab](url)

Please fix the non working PVR Items:
PVR.OpenTV
PVR.Details.Channel
and so on

**Comment by teichsta** [comment]
Hi @Dom1n1c,

> Please fix the non working PVR Items:
> PVR.OpenTV
> PVR.Details.Channel
> and so on

since you were able to insert more log statements will you probably be able to help us fixing this issue directly? The other maintainers and me would love to merge your PR.

Best, Thomas E.-E.

**Comment by Dom1n1c** [comment]
Hi @teichsta 

This is my item:

`String KodiLiving_OpenTVChannel "Open TV Channel [%s]"  					{xbmc=">[#Livingroom|PVR.OpenTV]"}`

When i use Player.Open it works as expected (for local media files or m3uwebcasts).
But i can not confirm this for PVR.OpenTV. (It should open a specific Channel from the IPVT Simple Addon)

The PVR.Details or PVR.GetChannelDetails seem to be outdated (Player.Lable and Player.Title shows the Channel information)

But back to PVR.OpenTV:
I have multiple Channels and i tried to use the Channel Number or the Channel Name.


The Error Message looks like this:
(It does not matter if i use the channel Name (ZDF, RTL or any other Station), or the Channelnumber

`2016-05-16 22:13:00.931 [DEBUG] [binding.xbmc.rpc.XbmcConnector] - channelName:ARD
2016-05-16 22:13:00.939 [ERROR] [enhab.binding.xbmc.rpc.RpcCall] - Error handling POST response from XBMC
org.openhab.binding.xbmc.rpc.RpcCall$RpcException: {code=-32602, message=Invalid params.}
	at org.openhab.binding.xbmc.rpc.RpcCall$1.onCompleted(RpcCall.java:145) ~[bundlefile:na]
	at org.openhab.binding.xbmc.rpc.RpcCall$1.onCompleted(RpcCall.java:1) ~[bundlefile:na]
	at com.ning.http.client.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:63) ~[async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:292) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyResponseFuture.done(NettyResponseFuture.java:319) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.markAsDone(NettyAsyncHttpProvider.java:1521) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.finishUpdate(NettyAsyncHttpProvider.java:1538) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2600(NettyAsyncHttpProvider.java:158) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2188) [async-http-client-1.8.4.jar:na]
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1220) [async-http-client-1.8.4.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.0.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.0.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]`

**Comment by 9037568** [comment]
If @TheNetStriker is still interested in pursuing the problem he originally described, I'd like to request an expanded description and a debug log.

If @Dom1n1c wants to pursue the problem he described, I'd like to request that a new ticket be opened for it and a debug log attached from a current build of OH.

Thanks!
