### ISSUE TITLE
Squeeze Server uses PercentType for playing time

### ISSUE THREAD

**Issue by SwissKid** [openhab/openhab1-addons#3542]
Here's the error:

```
Exception in thread "Squeeze Server Listener" java.lang.IllegalArgumentException: Value must be between 0 and 100
    at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:48)
    at org.openhab.core.library.types.PercentType.<init>(PercentType.java:33)
    at org.openhab.binding.squeezebox.internal.SqueezeboxBinding.numberChangeEvent(SqueezeboxBinding.java:245)
    at org.openhab.binding.squeezebox.internal.SqueezeboxBinding.currentPlayingTimeEvent(SqueezeboxBinding.java:173)
    at org.openhab.io.squeezeserver.SqueezePlayer.fireCurrentPlayingTimeEvent(SqueezePlayer.java:400)
    at org.openhab.io.squeezeserver.SqueezePlayer.setCurrentPlayingTime(SqueezePlayer.java:225)
    at org.openhab.io.squeezeserver.SqueezeServer$SqueezeServerListener.handleStatusMessage(SqueezeServer.java:703)
    at org.openhab.io.squeezeserver.SqueezeServer$SqueezeServerListener.handlePlayerUpdate(SqueezeServer.java:654)
    at org.openhab.io.squeezeserver.SqueezeServer$SqueezeServerListener.run(SqueezeServer.java:559)
```

This is an issue because of (in Binding)

```
public void currentPlayingTimeEvent(PlayerEvent event) {
    numberChangeEvent(event.getPlayerId(), CommandType.PLAYTIME, event.getPlayer().getCurrentPlayingTime());
}
```

...

```
private void numberChangeEvent(String playerId, CommandType commandType, int newState) {
    logger.debug("SqueezePlayer " + playerId + " -> " + commandType.getCommand() + ": " + Integer.toString(newState));
    for (String itemName : getItemNames(playerId, commandType)) {
        eventPublisher.postUpdate(itemName, new PercentType(newState));
    }
}
```

Which is no bueno when the "newState" is the number of seconds in a song (often over 100). My suggestion would be to change it to a string type.
##

**Comment by 9037568** [comment]
Here's a [test jar](https://github.com/openhab/openhab/files/678143/org.openhab.binding.squeezebox-1.9.0-SNAPSHOT.zip) that should fix this.
