### ISSUE TITLE
[astro] NullPointerException

### ISSUE THREAD

**Issue by watou** [openhab/openhab1-addons#3592]
```
2015-12-22 04:49:00.027 [ERROR] [org.quartz.core.JobRunShell   ] - Job Astro.Season threw an unhandled Exception: 
java.lang.NullPointerException: null
    at java.util.Hashtable.put(Hashtable.java:459) ~[na:1.8.0]
    at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86) ~[na:na]
    at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78) ~[na:na]
    at org.openhab.binding.astro.internal.job.ItemJob.executeJob(ItemJob.java:25) ~[na:na]
    at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:45) ~[na:na]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-all-2.1.7.jar:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
2015-12-22 04:49:00.039 [ERROR] [org.quartz.core.ErrorLogger   ] - Job (Astro.Season threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
    at org.quartz.core.JobRunShell.run(JobRunShell.java:224) ~[quartz-all-2.1.7.jar:na]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.lang.NullPointerException: null
    at java.util.Hashtable.put(Hashtable.java:459) ~[na:1.8.0]
    at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:86) ~[na:na]
    at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78) ~[na:na]
    at org.openhab.binding.astro.internal.job.ItemJob.executeJob(ItemJob.java:25) ~[na:na]
    at org.openhab.binding.astro.internal.job.AbstractBaseJob.execute(AbstractBaseJob.java:45) ~[na:na]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-all-2.1.7.jar:na]
    ... 1 common frames omitted
```

This looks like the `itemName` key was not in the `jobDataMap` [in this code](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/ItemJob.java#L25).  @gerrieg, could you look at this?
##

**Comment by gerrieg** [comment]
Currently i have no idea how this can happen. Can you please post your season items?

It seems to be a event job if the season changes, but there must be a itemName: [code] (https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/bus/PlanetPublisher.java#L140)

**Comment by watou** [comment]
Here are all the items with astro bindings in my openHAB server:
```
DateTime SunriseTime "Sunrise [%1$tH:%1$tM]" { astro="planet=sun, type=rise, property=start" }
DateTime SunsetTime  "Sunset [%1$tH:%1$tM]"  { astro="planet=sun, type=set, property=end" }
```

**Comment by gerrieg** [comment]
The only thing i can imagine is that you had a reload of the items file and that you previously had a astro event binding (Switch item) in your items. Can that be?

**Comment by watou** [comment]
Oddly, no.  I have only had those two `DateTime` items defined.

**Comment by 9037568** [comment]
Not reproducible?
