### ISSUE TITLE
Add support for Pilight

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab1-addons#4236]
The pilight-binding 1-8-1 do not work with oh2.
Here is the exception:
`2016-03-28 17:08:11.620 [ERROR] [org.openhab.binding.pilight         ] - [org.openhab.binding.pilight.binding(143)] The addBindingProvider method has thrown an exception
java.lang.NullPointerException
    at org.openhab.binding.pilight.internal.PilightBinding.checkItemState(PilightBinding.java:389)
    at org.openhab.binding.pilight.internal.PilightBinding.allBindingsChanged(PilightBinding.java:367)
    at org.openhab.core.binding.AbstractBinding.addBindingProvider(AbstractBinding.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497)[:1.8.0_66]
    at org.apache.felix.scr.impl.helper.BaseMethod.invokeMethod(BaseMethod.java:222)
    at org.apache.felix.scr.impl.helper.BaseMethod.access$500(BaseMethod.java:37)
    at org.apache.felix.scr.impl.helper.BaseMethod$Resolved.invoke(BaseMethod.java:615)
    at org.apache.felix.scr.impl.helper.BaseMethod.invoke(BaseMethod.java:499)
    at org.apache.felix.scr.impl.helper.BindMethod.invoke(BindMethod.java:41)
    at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1660)
    at org.apache.felix.scr.impl.manager.DependencyManager.open(DependencyManager.java:1495)
    at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:265)[28:org.apache.felix.scr:2.0.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:113)[28:org.apache.felix.scr:2.0.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:866)[28:org.apache.felix.scr:2.0.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:833)[28:org.apache.felix.scr:2.0.2]
    at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:774)[28:org.apache.felix.scr:2.0.2]
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_66]
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
    at org.apache.felix.cm.impl.helper.BaseTracker.getRealService(BaseTracker.java:201)[7:org.apache.felix.configadmin:1.8.8]
    at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:102)[7:org.apache.felix.configadmin:1.8.8]
    at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
    at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1753)[7:org.apache.felix.configadmin:1.8.8]
    at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
    at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_66]`
##

**Comment by watou** [comment]
Could you instead try the 1.9.0-SNAPSHOT version [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.pilight/target/org.openhab.binding.pilight-1.9.0-SNAPSHOT.jar)?

**Comment by LukaNoah** [comment]
With the 1.9.0 snapshot I got no errors, but also no values...

**Comment by LukaNoah** [comment]
Here is the log

`2016-03-29 19:55:30.858 [INFO ] [ng.pilight.internal.PilightConnector] - Established connection to pilight server at 192.168.178.120:5000
2016-03-29 19:55:30.872 [INFO ] [ng.pilight.internal.PilightConnector] - Established connection to pilight server at 192.168.178.121:5000
...
2016-03-29 19:55:31.083 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'PiLight.items'
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RPI_Master bound to device rpi, property temperature
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:Bad item Temp_RPI_Slave1 bound to device rpi, property temperature
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item AZ_Temperature bound to device Arbeiten, property temperature
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item AZ_Humidity bound to device Arbeiten, property humidity
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:Bad item Bad_Temperature bound to device Bad, property temperature
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:Bad item Bad_Humidity bound to device Bad, property humidity
2016-03-29 19:55:31.083 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:Bad item Therme_VL_Temperature bound to device Therme1, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Garage_Temperature bound to device Garage, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Garage_Humidity bound to device Garage, property humidity
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item SZ_Temperature bound to device Schlafen, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item SZ_Humidity bound to device Schlafen, property humidity
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item FSD1 bound to device FSD_BS_A
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item FSD2 bound to device FSD_BS_B
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item FSD3 bound to device FSD_BS_C
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_Flur bound to device VL_Flur, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_Flur bound to device RL_Flur, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_Kueche bound to device VL_Kueche, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_Kueche bound to device RL_Kueche, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_EZ bound to device VL_Essen, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_EZ bound to device RL_Essen, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_WZ1 bound to device VL_WZ1, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_WZ1 bound to device RL_WZ1, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_WZ2 bound to device VL_WZ2, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_WZ2 bound to device RL_WZ2, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_AZ bound to device VL_Arbeiten, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_AZ bound to device RL_Arbeiten, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_Bad bound to device VL_Bad, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_Bad bound to device RL_Bad, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_VL_Gesamt bound to device VL_Gesamt, property temperature
2016-03-29 19:55:31.099 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:AZ item Temp_RL_Gesamt bound to device RL_Gesamt, property temperature`

refreshes are not visible ...
(pilight-binding 1.9 / oh2)

**Comment by LukaNoah** [comment]
pilight-binding 1.9.0 - oh2

today with message

`2016-04-01 18:52:33.585 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/G:/openhab-online-2.0/addons/org.openhab.binding.pilight-1.9.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.pilight [138]
  Unresolved requirement: Import-Package: org.openhab.core.binding

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)[org.eclipse.osgi-3.10.2.v20150203-1939.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1207)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:504)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[8:org.apache.felix.fileinstall:3.5.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[8:org.apache.felix.fileinstall:3.5.0]`

**Comment by OzZyHH** [comment]
Just a small update:
I am using org.openhab.binding.pilight-1.11.0-SNAPSHOT.jar which works fine on OH2.1 stable. The only annoying thing is the following NPE on every startup:
`2017-09-21 18:19:52.223 [ERROR] [org.openhab.binding.pilight         ] - [org.openhab.binding.pilight.binding(9)] The addBindingProvider method has thrown an
java.lang.NullPointerException
        at org.openhab.binding.pilight.internal.PilightBinding.checkItemState(PilightBinding.java:401)
        at org.openhab.binding.pilight.internal.PilightBinding.allBindingsChanged(PilightBinding.java:379)
        at org.openhab.core.binding.AbstractBinding.addBindingProvider(AbstractBinding.java:61)
        at org.openhab.binding.pilight.internal.PilightBinding.addBindingProvider(PilightBinding.java:241)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_131]
        at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:224)
        at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39)
        at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:617)
        at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:501)
        at org.apache.felix.scr.impl.inject.BindMethod.invoke(BindMethod.java:655)
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1722)
        at org.apache.felix.scr.impl.manager.DependencyManager.open(DependencyManager.java:1556)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:260)[32:org.apache.felix.scr:2.0.6
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:108)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)[32:org.apache.felix.scr:2.0.6]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_131]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)[org.eclipse.osgi-3.10.101.v20150820-1432
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)[org.eclipse.osgi-3.10.101.v20150820
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39)[10:com.eclipsesource.jaxrs.publisher:5.3.1.20160
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)[org.osgi.core-6.0.0.jar:]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)[org.osgi.core-6.0.0.jar:]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)[org.eclipse.osgi-3.10.101.v2015
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)[org.eclipse.osgi-3.10.101.v20150
 ...`

Is it also possible to add this to the common legacy bindings? I don't want to handle this seperatly in my docker setup

**Comment by 9037568** [comment]
Going to suggest that if any of these symptoms are still occurring in current builds, a thread should be started in the community forum.
