### ISSUE TITLE
z-wave.me WallC-2 parameter error in habmin

### ISSUE THREAD

**Issue by LeoVe** [openhab/openhab1-addons#4265]
Thanks for the good work !

I have installed and included in the network a WALLC-2. The zwaveme device is recognized as a Popp 9303 Wall controller.

I would like to configure it with a direct association to a Fibaro dimmer 2. The desired operation is as described in the manual of the Wallc-2 as "2 groups are controlled with two buttons (parameter 1/2 = 1).

I think I need to set parameters 11 and 12 to 1 (Switch on/of and dim).
The problem is that habmin (Openhab/zwave binding) is not accepting this setting if I enter it through habmin.
In the Openhab log is this entry:

2016-03-22 11:59:40.713 [ERROR] [.a.h.ReflectorServletProcessor] - onRequest()
java.lang.NumberFormatException: For input string: "Switch on/off and Dim (send Basic Set and Switch Multilevel) "
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_73]
at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_73]
at java.lang.Integer.valueOf(Integer.java:766) ~[na:1.8.0_73]
at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.doSet(ZWaveConfiguration.java:1179) ~[bundlefile:na]
at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.putSet(ZWaveConfigResource.java:129) ~[na:na]
....

I'm using Openhab v1.8.2 with z-wave binding 1.9.0 (v 1.8.2 same error)

Any suggestions on what could be the matter?

Thanks,

Leo
##

**Comment by 9037568** [comment]
@LeoVe, it looks to me like this is a habmin problem. I'd suggest opening a discussion in the community forum. There is a separate issue tracker for habmin, also.
