### ISSUE TITLE
[Denon] Configuration of two instances throws null pointer exception

### ISSUE THREAD

**Issue by amut41** [openhab/openhab1-addons#4512]
## Expected Behavior

When two instances are configured, eg.

```
denon:avr2113.host=DENON-AVR-2113
denon:ceol.host=CEOL-piccolo
```

then it should be possible to control both devices.
## Current Behavior

As soon as two instances are configured, the following error occurs in openhab.log:

```
2016-07-03 21:26:59.561 [ERROR] [AbstractGenericBindingProvider] - Binding org.openhab.binding.denon.internal.DenonBinding threw an exception: 
java.lang.NullPointerException: null
    at org.openhab.binding.denon.internal.DenonBinding.getConnector(DenonBinding.java:269) ~[na:na]
    at org.openhab.binding.denon.internal.DenonBinding.bindingChanged(DenonBinding.java:104) ~[na:na]
    at org.openhab.model.item.binding.AbstractGenericBindingProvider.notifyListeners(AbstractGenericBindingProvider.java:118) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.model.item.binding.AbstractGenericBindingProvider.addBindingConfig(AbstractGenericBindingProvider.java:112) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.binding.denon.internal.DenonGenericBindingProvider.processBindingConfiguration(DenonGenericBindingProvider.java:81) [bundlefile:na]
    at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:348) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:324) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:171) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:390) [org.openhab.model.item_1.8.2.jar:na]
    at org.openhab.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:159) [org.openhab.model.core_1.8.2.jar:na]
    at org.openhab.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:100) [org.openhab.model.core_1.8.2.jar:na]
    at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:142) [org.openhab.model.core_1.8.2.jar:na]
    at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) [org.openhab.model.core_1.8.2.jar:na]
```
## Context

It seems I'm not the only one getting this error, please see [Two instances possible in Denon binding?](https://community.openhab.org/t/two-instances-possible-in-denon-binding/4847)
## Your Environment
- Version used: 1.8.2
- Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): n/a
- Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Jessie
##

**Comment by idserda** [comment]
Thanks for reporting this, I'll look into it.

**Comment by xsnrg** [comment]
I am about to try two as well.  Any updates?  Thanks.

**Comment by amut41** [comment]
Does anybody have the chance to look into it?

**Comment by watou** [comment]
@xsnrg @amut41 If you could provide DEBUG logging and your relevant lines from openhab.cfg and your item definitions, I will take a look (or @idserda if he prefers).

**Comment by 9037568** [comment]
I was unable to reproduce this failure tonight using 1.8.3.

Here's the debug output, showing two occurrences of "Denon receiver configured", each with the appropriate IP as defined in openhab.cfg...
````
denon:shasta.host=192.168.1.70
denon:fanta.host=8.8.8.8
````

````
   23:48:13.112 [DEBUG] [.denon.internal.DenonActivator:34   ] - Denon binding has been started.                                                                
   23:48:13.118 [DEBUG] [.b.denon.internal.DenonBinding:114  ] - Denon all bindings changed                                                                     
   23:48:13.119 [DEBUG] [.b.denon.internal.DenonBinding:141  ] - Denon binding updated                                                                          
   23:48:13.119 [DEBUG] [.b.denon.internal.DenonBinding:190  ] - Denon receiver configured at 192.168.1.70                                                      
   23:48:13.265 [DEBUG] [b.denon.internal.DenonListener:46   ] - Denon listener created                                                                         
   23:48:13.281 [DEBUG] [.denon.internal.DenonConnector:493  ] - Refreshing URL: http://192.168.1.70:80/goform/Deviceinfo.xml                                   
   23:48:13.281 [DEBUG] [b.denon.internal.DenonListener:104  ] - Connecting to 192.168.1.70                                                                     
   [...]
   23:48:59.719 [DEBUG] [.b.denon.internal.DenonBinding:190  ] - Denon receiver configured at 8.8.8.8                                                           
   23:48:59.803 [DEBUG] [b.denon.internal.DenonListener:46   ] - Denon listener created                                                                         
   23:48:59.803 [DEBUG] [.denon.internal.DenonConnector:493  ] - Refreshing URL: http://8.8.8.8:80/goform/Deviceinfo.xml                                        
   23:48:59.803 [DEBUG] [b.denon.internal.DenonListener:104  ] - Connecting to 8.8.8.8                                                                          
````

I also tried using hostnames instead of dotted quads, but got the same result.
