### ISSUE TITLE
[Openhabcloud] Throws "Unresolved compilation problems" exception at runtime

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab1-addons#4999]
## Current Behavior

When attempting to use the openhabcloud io transport, this error occurs:
````
13:02:52.451 [DEBUG] [o.o.i.o.internal.CloudClient  :149  ] - Manager.EVENT_TRANSPORT
13:02:52.451 [DEBUG] [o.o.i.o.internal.CloudClient  :154  ] - Transport.EVENT_REQUEST_HEADERS
13:02:52.466 [DEBUG] [o.o.i.o.internal.CloudClient  :154  ] - Transport.EVENT_REQUEST_HEADERS
13:02:52.603 [DEBUG] [o.o.i.o.internal.CloudClient  :168  ] - Socket.IO connected
13:02:52.619 [INFO ] [o.o.i.o.internal.CloudClient  :235  ] - Connected to the openHAB Cloud service (UUID = c..., local base URL = http://localhost:8080)
13:02:52.703 [ERROR] [io.socket.thread.EventThread  :82   ] - Task threw exception
java.lang.Error: Unresolved compilation problems: 
	CONNECTOR_SELECT_CHANNEL cannot be resolved or is not a field
	The method setMaxConnectionsPerAddress(int) is undefined for the type HttpClient
	The method setTimeout(int) is undefined for the type HttpClient

	at org.openhab.io.openhabcloud.internal.CloudClient.startJetty(CloudClient.java:208) ~[na:na]
	at org.openhab.io.openhabcloud.internal.CloudClient.onConnect(CloudClient.java:238) ~[na:na]
	at org.openhab.io.openhabcloud.internal.CloudClient$2.call(CloudClient.java:170) ~[na:na]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[na:na]
	at io.socket.client.Socket.access$601(Socket.java:19) ~[na:na]
	at io.socket.client.Socket$5.run(Socket.java:177) ~[na:na]
	at io.socket.thread.EventThread.exec(EventThread.java:55) ~[na:na]
	at io.socket.client.Socket.emit(Socket.java:173) ~[na:na]
	at io.socket.client.Socket.onconnect(Socket.java:387) ~[na:na]
	at io.socket.client.Socket.onpacket(Socket.java:287) ~[na:na]
	at io.socket.client.Socket.access$100(Socket.java:19) ~[na:na]
	at io.socket.client.Socket$2$2.call(Socket.java:111) ~[na:na]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[na:na]
	at io.socket.client.Manager.ondecoded(Manager.java:407) ~[na:na]
	at io.socket.client.Manager.access$1600(Manager.java:20) ~[na:na]
	at io.socket.client.Manager$7.call(Manager.java:383) ~[na:na]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[na:na]
	at io.socket.parser.Parser$Decoder.add(Parser.java:157) ~[na:na]
	at io.socket.client.Manager.ondata(Manager.java:399) ~[na:na]
	at io.socket.client.Manager.access$1000(Manager.java:20) ~[na:na]
	at io.socket.client.Manager$2.call(Manager.java:350) ~[na:na]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[na:na]
	at io.socket.engineio.client.Socket.onPacket(Socket.java:511) ~[na:na]
	at io.socket.engineio.client.Socket.access$1000(Socket.java:31) ~[na:na]
	at io.socket.engineio.client.Socket$5.call(Socket.java:313) ~[na:na]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[na:na]
	at io.socket.engineio.client.Transport.onPacket(Transport.java:134) ~[na:na]
	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17) ~[na:na]
	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124) ~[na:na]
	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251) ~[na:na]
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134) ~[na:na]
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106) ~[na:na]
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111) ~[na:na]
	at io.socket.thread.EventThread$2.run(EventThread.java:80) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_112]
````

## Your Environment

* OH 1.8.3 with openhabcloud 1.9.0 snapshot
* Windows 10
* Java 8

**Comment by watou** [comment]
Are you referring to the released version [linked here](https://github.com/openhab/openhab1-addons/wiki/openHAB-Cloud-Connector#installation), or one you built?

**Comment by 9037568** [comment]
It was one I built from master at the time. I'll retry using the one from your link.

**Comment by 9037568** [comment]
The linked official version does not produce this error, so for now we'll assume there was some problem with my build environment...
