### ISSUE TITLE
[caldavio] empty event titles crash calendar import

### ISSUE THREAD

**Issue by buxit** [openhab/openhab1-addons#5008]
if there is a calendar event with an empty title, the importer crashes and imports no other events.

```
2017-01-17 06:10:11.475 [ERROR] [caldav.internal.job.EventReloaderJob] - error while loading calendar entries: null
java.lang.NullPointerException
    at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:321)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:279)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:111)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201610101820]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201610101820]
2017-01-17 06:10:11.476 [INFO ] [org.quartz.core.JobRunShell         ] - Job event-reloader.commands threw a JobExecutionException:
org.quartz.JobExecutionException: error while loading calendar entries [See nested exception: java.lang.NullPointerException]
    at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:134)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201610101820]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[104:org.eclipse.smarthome.core.scheduler:0.9.0.201610101820]
Caused by: java.lang.NullPointerException
    at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:321)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:279)[199:org.openhab.io.caldav:1.9.0.201610120713]
    at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:111)[199:org.openhab.io.caldav:1.9.0.201610120713]
    ... 2 more
```

**Comment by 9037568** [comment]
Which version of OH is this from?

**Comment by buxit** [comment]
i tested this with a prerelease version of oh 2.0 from winter 2016/2017. not sure how to read out the version of oh as it is conglomerate of lots of different packages.

org.openhab.io.caldav:1.9.0.201610120713 apparently doesn't give enough info?

**Comment by buxit** [comment]
branch beta3 seems to match. see:
https://github.com/openhab/openhab1-addons/blob/beta3/bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java#L346
https://github.com/openhab/openhab1-addons/blob/beta3/bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/job/EventReloaderJob.java#L346

**Comment by 9037568** [comment]
Here's a [test jar](https://drive.google.com/open?id=0B8vYheWfObP9cGJwUWJXQnBYdXc) that I think should fix the problem. I've been unable to verify as I can't find a way to set a null title in Google calendar.

Can you try this out and see what you get?

**Comment by buxit** [comment]
still looks similar:
```
16:43:04.387 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-binding-caldav-command1'
16:43:04.402 [INFO ] [smarthome.event.ExtensionEvent      ] - Extension 'binding-caldav-command1' has been installed.
16:43:19.787 [ERROR] [caldav.internal.job.EventReloaderJob] - error while loading calendar entries: null
java.lang.NullPointerException
	at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:397)[180:org.openhab.io.caldav:1.10.0.201703260421]
	at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:316)[180:org.openhab.io.caldav:1.10.0.201703260421]
	at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:135)[180:org.openhab.io.caldav:1.10.0.201703260421]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)[102:org.eclipse.smarthome.core.scheduler:0.9.0.201612171108]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)[102:org.eclipse.smarthome.core.scheduler:0.9.0.201612171108]
```

(for future tests: is there a faster alternative to `rm -r cache` in order to make it load the new code?)

**Comment by 9037568** [comment]
It appears I overlooked an occurrence of the getSummary() call. I updated the jar; try downloading it again and see what you get.

I wouldn't have thought clearing the cache would be necessary, though.

**Comment by buxit** [comment]
this seems to fix it.

**Comment by 9037568** [comment]
Great. I have a little testing left to do, then I'll create a PR.

**Comment by buxit** [comment]
i wonder if it wouldn't make more sense to return a valid value from `getSummary()`, even if the title was empty. similar crashes may otherwise surface in other places.

**Comment by 9037568** [comment]
We don't have control of getSummary(), since it's an ical4j method.

You could try logging a defect against ical4j.
