### ISSUE TITLE
[jsonpath] Causes an exception when asked for the last element in a one element array

### ISSUE THREAD

**Issue by ajw107** [openhab/openhab1-addons#5034]
## Expected Behavior
Using either `[(@.length-1)]` or `[(:-1)]` to return the last element in an array which is only one element long, should return that element

## Current Behavior
A TransformationException is caught instead, showing this in the logs (one example of many, all the same, as you can see the last Rep array only contains one weather data element, which it should return):
```
2017-01-24 00:54:45.936 [ERROR] [ab.binding.http.internal.HttpBinding] - Transformation 'JSONPATH($.SiteRep.DV.Location.Period[(@.length-1)].Rep[(@.length-1)].Pt)' threw an exception. [response={"SiteRep":{"Wx":{"Param":[{"name":"G","units":"mph","$":"Wind Gust"},{"name":"T","units":"C","$":"Temperature"},{"name":"V","units":"m","$":"Visibility"},{"name":"D","units":"compass","$":"Wind Direction"},{"name":"S","units":"mph","$":"Wind Speed"},{"name":"W","units":"","$":"Weather Type"},{"name":"P","units":"hpa","$":"Pressure"},{"name":"Pt","units":"Pa\/s","$":"Pressure Tendency"},{"name":"Dp","units":"C","$":"Dew Point"},{"name":"H","units":"%","$":"Screen Relative Humidity"}]},"DV":{"dataDate":"2017-01-24T00:00:00Z","type":"Obs","Location":{"i":"3238","lat":"55.02","lon":"-1.88","name":"ALBEMARLE","country":"ENGLAND","continent":"EUROPE","elevation":"146.0","Period":[{"type":"Day","value":"2017-01-23Z","Rep":[{"D":"W","H":"87.0","P":"1025","S":"7","T":"2.2","V":"6000","W":"8","Pt":"R","Dp":"0.3","$":"0"},{"D":"W","H":"86.4","P":"1025","S":"7","T":"2.3","V":"6000","W":"8","Pt":"R","Dp":"0.3","$":"60"},{"D":"W","H":"88.4","P":"1025","S":"6","T":"2.4","V":"6000","W":"8","Pt":"R","Dp":"0.7","$":"120"},{"D":"W","H":"87.1","P":"1025","S":"6","T":"2.5","V":"6000","W":"8","Pt":"S","Dp":"0.6","$":"180"},{"D":"W","H":"87.7","P":"1025","S":"5","T":"2.4","V":"6000","W":"8","Pt":"F","Dp":"0.6","$":"240"},{"D":"WSW","H":"88.4","P":"1025","S":"6","T":"2.4","V":"5000","W":"8","Pt":"F","Dp":"0.7","$":"300"},{"D":"W","H":"88.2","P":"1025","S":"8","T":"1.8","V":"5000","W":"8","Pt":"F","Dp":"0.1","$":"360"},{"D":"W","H":"92.4","P":"1025","S":"6","T":"0.2","V":"3600","W":"0","Pt":"R","Dp":"-0.7","$":"420"},{"D":"W","H":"94.9","P":"1026","S":"3","T":"-1.1","V":"2200","W":"5","Pt":"R","Dp":"-1.6","$":"480"},{"D":"WSW","H":"96.3","P":"1026","S":"2","T":"-1.2","V":"2000","W":"5","Pt":"R","Dp":"-1.5","$":"540"},{"D":"WSW","H":"97.3","P":"1026","S":"2","T":"-0.2","V":"2200","W":"5","Pt":"R","Dp":"-0.5","$":"600"},{"D":"W","H":"91.5","P":"1026","S":"6","T":"1.8","V":"4100","W":"1","Pt":"R","Dp":"0.6","$":"660"},{"D":"W","H":"89.0","P":"1026","S":"7","T":"2.3","V":"4600","W":"1","Pt":"F","Dp":"0.7","$":"720"},{"D":"W","H":"87.1","P":"1025","S":"5","T":"3.5","V":"5000","W":"1","Pt":"F","Dp":"1.6","$":"780"},{"D":"WNW","H":"87.2","P":"1025","S":"5","T":"3.4","V":"4800","W":"1","Pt":"F","Dp":"1.5","$":"840"},{"D":"W","H":"85.9","P":"1024","S":"1","T":"3.5","V":"5000","W":"3","Pt":"F","Dp":"1.4","$":"900"},{"D":"E","H":"86.5","P":"1024","S":"1","T":"3.6","V":"6000","W":"7","Pt":"F","Dp":"1.6","$":"960"},{"D":"SE","H":"85.8","P":"1024","S":"3","T":"3.2","V":"7000","W":"7","Pt":"F","Dp":"1.1","$":"1020"},{"D":"S","H":"89.1","P":"1024","S":"2","T":"2.4","V":"5000","W":"7","Pt":"F","Dp":"0.8","$":"1080"},{"D":"WSW","H":"88.8","P":"1024","S":"1","T":"2.0","V":"7000","W":"7","Pt":"F","Dp":"0.4","$":"1140"},{"D":"SSW","H":"92.4","P":"1024","S":"2","T":"2.4","V":"7000","W":"8","Pt":"F","Dp":"1.3","$":"1200"},{"D":"S","H":"91.6","P":"1024","S":"3","T":"2.7","V":"10000","W":"2","Pt":"F","Dp":"1.5","$":"1260"},{"D":"SSE","H":"94.4","P":"1023","S":"5","T":"2.2","V":"8000","W":"5","Pt":"F","Dp":"1.4","$":"1320"},{"D":"S","H":"92.4","P":"1023","S":"3","T":"2.4","V":"9000","W":"0","Pt":"F","Dp":"1.3","$":"1380"}]},{"type":"Day","value":"2017-01-24Z","Rep":{"D":"S","H":"94.9","P":"1023","S":"3","T":"2.1","V":"9000","W":"5","Pt":"F","Dp":"1.4","$":"0"}}]}}}}]
org.openhab.core.transform.TransformationException: An error occured while transforming JSON expression.
	at org.openhab.core.transform.TransformationHelper$TransformationServiceDelegate.transform(TransformationHelper.java:63)[177:org.openhab.core.compat1x:2.1.0.201701231847]
	at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:189)[210:org.openhab.binding.http:1.10.0.201701231228]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[177:org.openhab.core.compat1x:2.1.0.201701231847]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)[177:org.openhab.core.compat1x:2.1.0.201701231847]
```
Not sure if this is a problem with openhab's binding or the external JSONPATH library though.

## Possible Solution
As I'm not sure if the poroblem is in the openhab binding or JSONPATH library, I can;t say what is exactly causing the problem, at a guess I'd say it was a bounds issue.

## Steps to Reproduce (for bugs)
Either using the data in the logs above, or just with any JSON which contains an array with only one element use either `[(@.length-1)]` or `[(:-1)]` to retreieve that element, the exception will then be thrown.

## Context
I'm using this to parse the data from the MET Office Weather datapoint webfeed, and occurs consistently between the hours of midnight and 1am.  This is becasue the webfeed always contains the last 24 weather observations (hence why getting the last one, as it should eb the 'current' observation).  But between midnight and 1am you get 23 observations from the previous day, and one for the current day, tripping the bug.

## Your Environment
Openhab2 build 752 JSONPATH transformation-jsonpath - 2.1.0.SNAPSHOT (from the kar file associated with the 752 build), but the problem is not limited to only this addon version
Windows 10x64 with Java 1.8.0 build 121

**Comment by watou** [comment]
Could you take the original JSON and the JsonPath expression and plug them into an online JsonPath tester or two, and see what they say?

**Comment by 9037568** [comment]
I tried two different online evaluators:
>jsonpath.com
>https://jsonpath.curiousconcept.com/

Both failed on this:
>$.SiteRep.DV.Location.Period[(@.length-1)].Rep[(@.length-1)]

But succeeded with this:
>$.SiteRep.DV.Location.Period[(@.length-1)].Rep

Which makes this sounds like it's an error in JsonPath.
