### ISSUE TITLE
JDBC mariadb is using localhost ip instead that one from jdbc.conf

### ISSUE THREAD

**Issue by bigtarget** [openhab/openhab1-addons#5072]
Hello,

here is the log:

2017-02-07 11:04:26.130 [DEBUG] [org.openhab.persistence.jdbc        ] - ServiceEvent REGISTERED - {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={url=jdbc:mariadb://QNAP:3306/openhab, component.name=org.openhab.persistence.jdbc, service.config.category=persistence, driverClassName=org.mariadb.jdbc.Driver, service.config.description.uri=persistence:jdbc, user=openhab, service.pid=org.openhab.jdbc, service.config.label=JDBC Persistence, component.id=202, password=xxxxxxxxxxxxxxxxxx, service.id=338, service.bundleid=218, service.scope=bundle} - org.openhab.persistence.jdbc
2017-02-07 11:04:26.139 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::setItemRegistry
2017-02-07 11:04:26.141 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::activate: persistence service activated
2017-02-07 11:04:26.143 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::updateConfig
2017-02-07 11:04:26.145 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::JdbcConfiguration
2017-02-07 11:04:26.147 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: configuration size = 10
2017-02-07 11:04:26.150 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: user=openhab
2017-02-07 11:04:26.153 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: password exists? true
2017-02-07 11:04:26.155 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: url=jdbc:mariadb://QNAP:3306/openhab
2017-02-07 11:04:26.157 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: found serviceName = 'mariadb'
2017-02-07 11:04:26.159 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: Init Data Access Object Class: 'org.openhab.persistence.jdbc.db.JdbcMariadbDAO'
2017-02-07 11:04:26.161 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::initSqlTypes: Initialize the type array
2017-02-07 11:04:26.163 [DEBUG] [nhab.persistence.jdbc.db.JdbcBaseDAO] - JDBC::initSqlQueries: 'JdbcMariadbDAO'
2017-02-07 11:04:26.165 [DEBUG] [b.persistence.jdbc.db.JdbcMariadbDAO] - JDBC::initSqlTypes: Initialize the type array
2017-02-07 11:04:26.167 [DEBUG] [b.persistence.jdbc.db.JdbcMariadbDAO] - JDBC::initSqlQueries: 'JdbcMariadbDAO'
2017-02-07 11:04:26.169 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: dBDAO ClassName=org.openhab.persistence.jdbc.db.JdbcMariadbDAO
2017-02-07 11:04:26.172 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: enableLogTime false
2017-02-07 11:04:26.174 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: load JDBC-driverClass was successful: 'org.mariadb.jdbc.Driver'
2017-02-07 11:04:26.176 [DEBUG] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: configuration complete. service=jdbc
2017-02-07 11:04:26.177 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::pingDB
2017-02-07 11:04:26.178 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection isDriverAvailable: true
2017-02-07 11:04:26.179 [INFO ] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection: Driver is available::Yank setupDataSource
2017-02-07 11:04:26.220 [ERROR] [org.openhab.persistence.jdbc        ] - [org.openhab.persistence.jdbc(202)] The activate method has thrown an exception
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Access denied for user 'openhab'@'192.168.1.106' (using password: YES)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
        at org.knowm.yank.YankPoolManager.createPool(YankPoolManager.java:101)
        at org.knowm.yank.YankPoolManager.addDefaultConnectionPool(YankPoolManager.java:69)
        at org.knowm.yank.Yank.setupDefaultConnectionPool(Yank.java:705)
        at org.openhab.persistence.jdbc.internal.JdbcMapper.openConnection(JdbcMapper.java:171)
        at org.openhab.persistence.jdbc.internal.JdbcMapper.pingDB(JdbcMapper.java:49)
        at org.openhab.persistence.jdbc.internal.JdbcMapper.checkDBAccessability(JdbcMapper.java:195)
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.updateConfig(JdbcPersistenceService.java:218)
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.activate(JdbcPersistenceService.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
        at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:224)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:617)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:501)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:302)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.inject.ActivateMethod.invoke(ActivateMethod.java:294)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:297)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:108)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:748)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:670)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:609)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:426)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:273)[32:org.apache.felix.scr:2.0.6]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:2068)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:2036)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'openhab'@'192.168.1.106' (using password: YES)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:121)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.Driver.connect(Driver.java:110)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
        ... 34 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'openhab'@'192.168.1.106' (using password: YES)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:469)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:433)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:354)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:668)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:587)
        at org.mariadb.jdbc.Driver.connect(Driver.java:105)
        ... 37 more

**Comment by bigtarget** [comment]
My fault

I have created database accessed only from localhost.

DROP DATABASE openhab;CREATE DATABASE openhab CHARACTER SET utf8 COLLATE utf8_general_ci;GRANT ALL PRIVILEGES ON openhab.* TO 'openhab'@'%' IDENTIFIED BY 'xxxxxxxxxxx';

Fixed the issue.
