### ISSUE TITLE
[TinkerForge] Exception during event dispatch - updating LCD 20x4

### ISSUE THREAD

**Issue by JamesDodds** [openhab/openhab1-addons#5091]
Hi,

I'm using the TF 1.9.0 RC1 plugin, with the apt install of OpenHAB2. I've configured it to read from a TF Weatherstation setup. It reads the sensor data fine, but errors when updating the LCD (20x4 brick) characters.

> 23:35:11.694 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=openhab/command/TF_LCD] {bridgemarker=true, item=TF_LCD, command=TFNUM<213> 974} | {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/command/*, service.pid=org.openhab.tinkerforge, component.name=org.openhab.binding.tinkerforge.binding, component.id=242, service.id=390, service.bundleid=235, service.scope=bundle} | Bundle(org.openhab.binding.tinkerforge_1.9.0.RC1 [235])]
java.lang.UnsupportedOperationException
        at org.openhab.binding.tinkerforge.internal.model.impl.MBrickletLCD20x4Impl.write(MBrickletLCD20x4Impl.java:1035)[235:org.openhab.binding.tinkerforge:1.9.0.RC1]
        at org.openhab.binding.tinkerforge.internal.TinkerforgeBinding.internalReceiveCommand(TinkerforgeBinding.java:787)[235:org.openhab.binding.tinkerforge:1.9.0.RC1]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:97)[182:org.openhab.core.compat1x:2.0.0.RC1]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:42)[182:org.openhab.core.compat1x:2.0.0.RC1]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415)[6:org.apache.karaf.services.eventadmin:4.0.8]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:90)[6:org.apache.karaf.services.eventadmin:4.0.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

I thought that the ID's might be off, but they aren't.
I can turn the LCD backlight on and off, and it registers all four button presses. But it will not update the LCD itself.

Does anyone have any suggestions on what to try next?

**Comment by 9037568** [comment]
As you can see in the error log, this operation is not supported.
>java.lang.UnsupportedOperationException at org.openhab.binding.tinkerforge.internal.model.impl.MBrickletLCD20x4Impl.write(MBrickletLCD20x4Impl.java:1035)[235:org.openhab.binding.tinkerforge:1.9.0.RC1]

From [line 1035](https://github.com/openhab/openhab1-addons/blob/9691753d6671a3b173a75f710d9e09699144f649/bundles/binding/org.openhab.binding.tinkerforge/src/main/java/org/openhab/binding/tinkerforge/internal/model/impl/MBrickletLCD20x4Impl.java#L1035).

@theoweiss is the sme on this. Any thoughts?

**Comment by theoweiss** [comment]
Oops, thanks for reporting. The code generator removed the implementation, I have to revert this.

**Comment by JamesDodds** [comment]
Phew. I thought I was going bonkers or missing something. 
Do you need any more information?

**Comment by theoweiss** [comment]
No thanks, I know what's going wrong. I've made a fix and it would be great if you could test it. The fixed binding bundle is available from here: https://bintray.com/theoweiss/generic/download_file?file_path=lcd217%2Forg.openhab.binding.tinkerforge-1.10.0-SNAPSHOT.jar

**Comment by JamesDodds** [comment]
Worked a treat thanks @theoweiss

**Comment by 9037568** [comment]
Closed via merged PR.
