### ISSUE TITLE
Unable to use UDP incoming data with TCP/UDP Binding "Error while executing background thread UDP Refresh Service"

### ISSUE THREAD

**Issue by Chanete** [openhab/openhab1-addons#5110]
Hi, I'm trying to integrate in OH2 (with the OH1 TCP/UDP binding)  my already inplace arduinos that are controlling some lamps. 

My protocol is extremely easy I use UDP packets to send commands to arduinos, and arduinos respond with HTTP GET's over UDP.  Right now I have my own UDP2HTTP proxy that converts those HTTP requests to TCP and forward them to an apache that handle the requests. 

I want to remove the whole thing (apache and my app) and integrate those arduinos in Openhab. 

The outbound connections are working properly, I have a switch in OH that will send the proper command when activated but I'm stuck with the inbound connections.  My planis to write a javascript transformation that parses properly my URL into diferente variables in OH so, after that I could handle the state change of lights and some other data. 

To begin with the easiest thing I've set up an item like this: 

`String Arduino_TCP_rcv "ArduinoUDP [%s]"   {udp="<[*:8888:'']"}  `

This should store in Arduino_TCP_rcv the complete udp packet sent from the arduino. 

In the log you an see this: 
```
Received *GET /arduino/module_event.php?p=1&t=0&s=1&d=I&m=Cocina on the listener port from /192.168.1.253:53023
2017-02-21 19:15:15.377 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread UDP Refresh Service                                                                               
java.lang.NullPointerException                                                                                                                                                                                     
        at org.openhab.binding.tcp.protocol.internal.UDPBinding.parseBuffer(UDPBinding.java:156)[198:org.openhab.binding.tcp:1.9.0.b5]                                                                             
        at org.openhab.binding.tcp.AbstractDatagramChannelBinding.parseChanneledBuffer(AbstractDatagramChannelBinding.java:1014)[198:org.openhab.binding.tcp:1.9.0.b5]                                             
        at org.openhab.binding.tcp.AbstractDatagramChannelBinding.execute(AbstractDatagramChannelBinding.java:1551)[198:org.openhab.binding.tcp:1.9.0.b5]                                                          
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[179:org.openhab.core.compat1x:2.0.0.b5]                                                     
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)[179:org.openhab.core.compat1x:2.0.0.b5]    
```

what am I doing wrong??? I've read all post about udp binding, and tested almost everything, but I'm stuck. 

Can someone help me? 

I'm using

OH2    4.0.8 
binding-tcp1 - 1.9.0.b5 
Raspberry PI3 runnig Jessie

Thx!

**Comment by 9037568** [comment]
Looks to me like the provider was null.  I'll supply a test jar to try to confirm this.

Can you provide your configurations? (sitemap, items definitions and tcp settings)

**Comment by 9037568** [comment]
Here's the [test jar](https://drive.google.com/open?id=0B8vYheWfObP9UUpDLWFLanpYREk). Please make sure to remove the 1.9.0 jar when installing this one.

Drop the binding into debug mode before starting openHAB. After starting the system, you should see these lines of output in the log:
>parseBuffer constructed update: '[received update message will go here]'
No provider could be found for the item '[item name will go here]'

The first will be a debug message and the second a warning.
If you fail to get the first message, you haven't installed the new jar correctly.

Upload the newly generated log file so we can see what's happening.

**Comment by Chanete** [comment]
Thank you for your prompt response!!! 

I've installed the JAR you sent me and I've found what was the error.  The problem was that in my item definition: 
`String Arduino_TCP_rcv "ArduinoUDP [%s]" {udp="<[*:8888:'']"}`
8888 is the destination port  where arduinos send the info, sourceport  is a random port that changes everytime. Reading the new log files I've realized with the lastg message that what the binding expects there is the source port, not the destination port. So I've changed  the item to:  
`String Arduino_TCP_rcv "ArduinoUDP [%s]" {udp="<[*:*:'']"}`
and now it works!! 

Thank's for your help. 

One "cosmetic" thing. If I use display in the laraf console, I get the log like it's copied below, but if i go to /var/log/openhab2/openhab.log, there are a lot of ^@^@^@^@^@^ between "Cocina ^@^@^@^@^@^ on the listener"... like if it was an StringBuffer no emptied.

Thanks again!

```
2017-02-22 09:11:50.737 [DEBUG] [g.tcp.AbstractDatagramChannelBinding] - Received *GET /arduino/module_event.php?p=1&t=3799&s=0&d=I&m=Cocina  on the listener port from /192.168.1.253:49618
2017-02-22 09:11:50.739 [WARN ] [g.tcp.AbstractDatagramChannelBinding] - Received data *GET /arduino/module_event.php?p=1&t=3799&s=0&d=I&m=Cocina from an undefined remote end /192.168.1.253:49618. We will not process it
2017-02-22 09:11:50.740 [WARN ] [g.tcp.AbstractDatagramChannelBinding] - No channel is active or defined for the data we received from /192.168.1.253:49618. It will be discarded.       
```

**Comment by 9037568** [comment]
Glad you got it working. Please upload your log file for analysis so that we can debug the ^@ items.

**Comment by Chanete** [comment]
Sorry for the delay, I've been quite  busy with other projects... 

Here is the log as it appears if you vi /var/log/openhab2/openhab.log

```
2017-02-27 19:21:37.383 [WARN ] [g.tcp.AbstractDatagramChannelBinding] - When using address masks we will not verify if we are already listening to similar incoming connections                                 
2017-02-27 19:21:37.386 [INFO ] [g.tcp.AbstractDatagramChannelBinding] - We will accept data coming from the remote end *:*                                                                                      
2017-02-27 19:21:37.388 [INFO ] [g.tcp.AbstractDatagramChannelBinding] - We will accept data coming from the remote end with mask *:*                                                                            
2017-02-27 19:21:37.392 [DEBUG] [g.tcp.AbstractDatagramChannelBinding] - Setting up the inbound channel Channel [item=Arduino_TCP_rcv, command=0, direction=IN, remote=null, buffer=, isBlocking=false, isReconne
cting=false, channel=/0:0:0:0:0:0:0:0:8888, host=*, port=*]                                                                                                                                                      
2017-02-27 19:21:37.408 [DEBUG] [g.tcp.AbstractDatagramChannelBinding] - Setting up the outbound channel Channel [item=Light_map, command=OFF, direction=OUT, remote=/192.168.1.43:8888, buffer=, isBlocking=fals
e, isReconnecting=false, channel=, host=192.168.1.43, port=8888]                                                                                                                                                 
2017-02-27 19:21:37.412 [INFO ] [g.tcp.AbstractDatagramChannelBinding] - 'Connecting' the channel Channel [item=Light_map, command=OFF, direction=OUT, remote=/192.168.1.43:8888, buffer=, isBlocking=false, isRe
connecting=false, channel=, host=192.168.1.43, port=8888]                                                                                                                                                        
2017-02-27 19:21:37.416 [DEBUG] [g.tcp.AbstractDatagramChannelBinding] - Setting up the outbound assigned channel Channel [item=Light_map, command=ON, direction=OUT, remote=/192.168.1.43:8888, buffer=, isBlock
ing=false, isReconnecting=false, channel=/192.168.1.82:48103::/192.168.1.43:8888, host=192.168.1.43, port=8888]                                                                                                  
2017-02-27 19:21:37.419 [INFO ] [g.tcp.AbstractDatagramChannelBinding] - There is already an active channel sun.nio.ch.DatagramChannelImpl@f071fc for the remote end /192.168.1.43:8888                          
2017-02-27 19:22:41.110 [DEBUG] [g.tcp.AbstractDatagramChannelBinding] - Received *GET /arduino/module_event.php?p=1&t=3256&s=0&d=I&m=Cocina                                                                     
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ on the listener port from /192.168.1.242:52248
2017-02-27 19:22:41.113 [DEBUG] [ing.tcp.protocol.internal.UDPBinding] - parseBuffer constructed update: '*GET /arduino/module_event.php?p=1&t=3256&s=0&d=I&m=Cocina                                             
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@'
2017-02-27 19:22:41.114 [DEBUG] [ing.tcp.protocol.internal.UDPBinding] - transformed response is '*GET /arduino/module_event.php?p=1&t=3256&s=0&d=I&m=Cocina                                                     
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@'
```

**Comment by 9037568** [comment]
I'll see if I can reproduce without a log file. I'm guessing this is just bad logging that needs to be eliminated.
