### ISSUE TITLE
[plex] Plex binding not controlling Plex Media Player

### ISSUE THREAD

**Issue by Rtaxerxes** [openhab/openhab1-addons#5118]
I've upgraded my Rasplex player to use the latest Plex Media Player (PMP) for Raspberry Pi since the Alexa support doesn't worj with rasplex. Commands from Openhab don't work on PMP other than progress, state and title. 

Would it be possible to add support for PMP to the binding? I have noticed it seems to use port 32433 instead of 3005.

**Comment by nitruxa** [comment]
Any update on this?
when trying to control Plex via OpenHab this error throws:
```
[ERROR] [.binding.plex.internal.PlexConnector] - Error while sending command to Plex: Bad Request
<html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
```

**Comment by staehler** [comment]
Same here, can't control anything :-(

2018-05-23 19:24:56.494 [vent.ItemStateChangedEvent] - PlexWZVolume changed from 85 to 80
2018-05-23 19:24:56.571 [ome.event.ItemCommandEvent] - Item 'PlexWZVolume' received command 75
2018-05-23 19:24:56.870 [vent.ItemStateChangedEvent] - PlexWZVolume changed from 80 to 75
2018-05-23 19:24:56.873 [ome.event.ItemCommandEvent] - Item 'PlexWZVolume' received command 70
2018-05-23 19:24:57.004 [vent.ItemStateChangedEvent] - PlexWZVolume changed from 75 to 70
2018-05-23 19:24:57.006 [ome.event.ItemCommandEvent] - Item 'PlexWZVolume' received command 70

==> /var/log/openhab2/openhab.log <==
2018-05-23 19:24:57.052 [ERROR] [.binding.plex.internal.PlexConnector] - Error while sending command to Plex: Not Acceptable
2018-05-23 19:24:57.054 [ERROR] [.binding.plex.internal.PlexConnector] - Error while sending command to Plex: Not Acceptable
2018-05-23 19:24:57.157 [ERROR] [.binding.plex.internal.PlexConnector] - Error while sending command to Plex: Not Acceptable

**Comment by staehler** [comment]
Is there any progress?
Can't control my plex server, getting this log:
```
2018-09-22 19:56:16.561 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=openhab/command/PlexWZPause] {item=PlexWZPause, bridgemarker=true, command=ON, timestamp=1537638976373} | {org.osgi.service.event.EventHandler}={port=32400, service.id=503, service.bundleid=244, service.scope=bundle, refresh=5000, component.name=org.openhab.binding.plex.binding, component.id=314, token=z75wBj1uxSChxjyzDJx2, host=192.168.2.1, event.topics=openhab/command/*, service.pid=org.openhab.plex} | Bundle(org.openhab.binding.plex_1.13.0.201809111943 [244])]
java.lang.NullPointerException: null
        at org.openhab.binding.plex.internal.PlexConnector.getHost(PlexConnector.java:417) ~[?:?]
        at org.openhab.binding.plex.internal.PlexConnector.sendCommand(PlexConnector.java:238) ~[?:?]
        at org.openhab.binding.plex.internal.PlexBinding.internalReceiveCommand(PlexBinding.java:147) ~[?:?]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:94) ~[?:?]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```
I'm running openhab2  2.4.0~20180914230535-1
