### ISSUE TITLE
[KNX] received request with unkown cEMI data

### ISSUE THREAD

**Issue by jochenkluger** [openhab/openhab1-addons#5138]
Hello,
I am just migrating from openhab 1.7.1 to openhab 2. The old system ran on an ubuntu 14.04 LTS, the new one on an ubuntu 16.04 LTS. I installed openhab 2 from the repository following the instructions and installed the bindings via HABmin. Then I configured the knx binding in /etc/openhab2/services/knx.cfg like the old system:

ip=192.168.0.10
type=TUNNEL

And created a simple knx item by copying a part of the old configuration (the group is also defined):
Switch lightGroundFloorEntryCeiling     "Deckenlicht Eingangsbereich"                   (groupGroundFloorEntry, groupLights)    { knx="1/1/0+<1/1/1" }

Then I started the openhab2 service and took a look in the openhab.log:

2017-03-11 16:46:11.177 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '0_global_groups.items'
2017-03-11 16:46:11.341 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model '2_light.items'
2017-03-11 16:46:12.914 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
2017-03-11 16:46:13.009 [INFO ] [b.core.service.AbstractActiveService] - HTTP Refresh Service has been started
2017-03-11 16:46:13.221 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-03-11 16:46:13.486 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-03-11 16:46:13.617 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-03-11 16:46:13.792 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-03-11 16:46:13.897 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-03-11 16:46:13.924 [INFO ] [b.core.service.AbstractActiveService] - IRtrans Refresh Service has been started
2017-03-11 16:46:14.159 [INFO ] [nx.internal.connection.KNXConnection] - Established connection to KNX bus on 192.168.0.10:3671 in mode TUNNEL.
2017-03-11 16:46:14.232 [WARN ] [tuwien.auto.calimero                ] - KNXnet/IP Tunneling 192.168.0.10:3671: received request with unknown cEMI data$
tuwien.auto.calimero.exception.KNXFormatException: length of tpdu exceeds available data: 0xe2
        at tuwien.auto.calimero.cemi.CEMILDataEx.readPayload(CEMILDataEx.java:501)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.cemi.CEMILDataEx.<init>(CEMILDataEx.java:168)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.cemi.CEMIFactory.create(CEMIFactory.java:88)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.servicetype.ServiceRequest.<init>(ServiceRequest.java:83)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.servicetype.PacketHelper.getServiceRequest(PacketHelper.java:88)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.getServiceRequest(ConnectionBase.java:533)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.handleServiceType(KNXnetIPTunnel.java:166)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.ReceiverLoop.onReceive(ReceiverLoop.java:85)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.internal.UdpSocketLooper.loop(UdpSocketLooper.java:134)[213:org.openhab.binding.knx:1.9.0]
        at tuwien.auto.calimero.knxnetip.ReceiverLoop.run(ReceiverLoop.java:67)[213:org.openhab.binding.knx:1.9.0]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

I also tried several different configurations in the knx.cfg like 
busaddr=1.0.0
or
localIp=192.168.0.5

but nothing really helps. Any suggestions?

Best regards
Jochen

**Comment by 9037568** [comment]
Possibly related to #4903?
