### ISSUE TITLE
[mqtt] MQTT connection to broker was lost -- Connection lost (32109) - java.io.EOFException

### ISSUE THREAD

**Issue by metbril** [openhab/openhab1-addons#5160]
## Expected Behavior

Connection not lost.

## Current Behavior

Using openHABian 1.2, MQTT installed through `openhabian-config`
Installed mqtt1 binding.
Configured connection to external broker (CloudMQTT) for use with OwnTracks.

Every 20 seconds, it looks like the connection is lost.

**mqtt.cfg**
```
ext.url=ssl://mXX.cloudmqtt.com:2XXXX
ext.clientId=openhab
ext.user=openhab
ext.pwd=XXXXXXXXXX
```

**openhab.log**
```
2017-04-03 12:15:40.894 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to broker was lost
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:138)[213:org.openhab.io.transport.mqtt:1.9.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)[:1.8.0_121]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:56)[213:org.openhab.io.transport.mqtt:1.9.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:100)[213:org.openhab.io.transport.mqtt:1.9.0]
	... 1 more
2017-04-03 12:15:40.896 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to 'ext' was lost: Connection lost : ReasonCode 32109 : Cause : null
2017-04-03 12:15:40.899 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting connection helper to periodically try restore connection to broker 'ext'
```
## Possible Solution

?

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment

- openHABian 1.2
- latest Java, mosquitto etc.
- Raspberry Pi 3B

**Comment by 9037568** [comment]
Please attach a debug log.

**Comment by 9037568** [comment]
Also, what is your persistence configuration?

**Comment by rtvb** [comment]
I have set this logging:

```
log:set DEBUG org.openhab.binding.mqtt
```

which isn't more verbose.

 What do I have to set for debug logging of `[t.mqtt.internal.MqttBrokerConnection]`?

I don't have and don't need persistence, since I only use MQTT to get my OwnTracks messages from an external broker.

**mqtt.items**
```
String   Presence_RobertPhone_Raw        "iPhone Robert [%s]"    <text>    (gRobertPhone) {mqtt="<[ext:owntracks/robert/iphone:state:default]"}
```

**Comment by rtvb** [comment]
```
15:21:00.688 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'ext'
15:21:01.009 [DEBUG] [t.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'ext' on topic 'owntracks/robert/event'
15:21:01.044 [DEBUG] [t.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'ext' on topic 'owntracks/robert/iphone'
:
:
15:21:11.396 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to broker was lost
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:138)[213:org.openhab.io.transport.mqtt:1.9.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)[:1.8.0_121]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:56)[213:org.openhab.io.transport.mqtt:1.9.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:100)[213:org.openhab.io.transport.mqtt:1.9.0]
	... 1 more
15:21:11.401 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to 'ext' was lost: Connection lost : ReasonCode 32109 : Cause : null
15:21:11.403 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting connection helper to periodically try restore connection to broker 'ext'
:
:
15:21:21.405 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'ext'
15:21:21.771 [DEBUG] [t.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'ext' on topic 'owntracks/robert/event'
15:21:21.803 [DEBUG] [t.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'ext' on topic 'owntracks/robert/iphone'
```

**Comment by 1iveowl** [comment]
I am experience similar issue. 

This is added to the log every 10 second: 

> 2017-06-30 09:02:26.234 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'mqttbroker14'
2017-06-30 09:02:27.884 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to broker was lost
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)[197:org.openhab.io.transport.mqtt:1.10.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)[:1.8.0_121]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)[197:org.openhab.io.transport.mqtt:1.10.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)[197:org.openhab.io.transport.mqtt:1.10.0]
	... 1 more
2017-06-30 09:02:27.890 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to 'mqttbroker14' was lost: Connection lost : ReasonCode 32109 : Cause : null
2017-06-30 09:02:27.894 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting connection helper to periodically try restore connection to broker 'mqttbroker14'
2017-06-30 09:02:30.257 [INFO ] [binding.hue.handler.HueBridgeHandler] - Creating new user on Hue bridge 192.168.0.19 - please press the pairing button on the bridge.

**Comment by 1iveowl** [comment]
What version of MQTT is used? Is it 3.1.1?

**Comment by 9037568** [comment]
Yes, the client should be compatible with 3.1.1.

**Comment by 1iveowl** [comment]
Should be compatible with 3.1.1? Is it, or is it not? How do I verify for sure?

Using identical parameters, I can connect to my broker using Mosquitto. I can connect to my broker using MQTT.fx, which is using Oracle JDK 1.8.131 and paho, just like the MQTT Binding in OH2.1. 

Why can't I connect w/ my OH2.1 MQTT binding? I think I've tried pretty much all permutations I can come up with. I'm running out of ideas.

**Comment by 1iveowl** [comment]
Looks like it's a know issue [MQTT Binding and Azure IoTHub Error](https://community.openhab.org/t/mqtt-binding-and-azure-iothub-error/7902/2)

**Comment by xipero** [comment]
I still do have this problem running openhab 2.1.0-1 (Release Build) on a pine64 with a mosquitto server (v1.4.8) installed locally on the pine64.
2017-11-07 07:12:23.351 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to 'broker' was lost: Connection lost : ReasonCode 32109 : Cause : null
2017-11-07 07:12:23.353 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting connection helper to periodically try restore connection to broker 'broker'
2017-11-07 07:12:33.356 [INFO ] [t.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'broker'
2017-11-07 07:12:33.383 [ERROR] [t.mqtt.internal.MqttBrokerConnection] - MQTT connection to broker was lost
Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)[190:org.openhab.io.transport.mqtt:1.10.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)[:1.8.0_121]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)[190:org.openhab.io.transport.mqtt:1.10.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)[190:org.openhab.io.transport.mqtt:1.10.0]
	... 1 more

**Comment by KhamkarSagar** [comment]
if broker is held by other resources and if you are trying to post at same time,then MQTT gives MQTT connection lost error or -3 !
 For instance publisher and subscriber can't use broker simultaneously .
