### ISSUE TITLE
[Mail] SMTP port setting in configuration file will be ignored by add-on

### ISSUE THREAD

**Issue by nRaecheR** [openhab/openhab1-addons#5236]
## Expected Behavior

The mail action reads the  the given port in the configuration file and tries to connect to the SMTP server on that port when sending a mail via SMTP protocol.

## Current Behavior

The mail won't be send and an exception will be thrown in the openhab2.log. Instead of the configured port 587 the add-on tries to connect to port 465, which isn't available on the server. I've tried a lot of combinations for SSL/TLS/STARTTLS/unencrypted connections, it seems the ports are hardcoded for the specific protocols.

Here's the openhab2.log output (all domains replaced by domain.tld):
```
2017-07-02 11:56:55.430 [ERROR] [rg.openhab.action.mail.internal.Mail] - Could not send e-mail to 'openhab2@domain.tld'.
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.domain.tld:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
        at org.apache.commons.mail.Email.send(Email.java:1448)
        at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:157)
        at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:89)
        at org.openhab.action.mail.internal.Mail.sendMail(Mail.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_131]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1085)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeOperation(XbaseInterpreter.java:1060)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._invokeFeature(XbaseInterpreter.java:1046)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.invokeFeature(XbaseInterpreter.java:991)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.smarthome.model.script.interpreter.ScriptInterpreter.invokeFeature(ScriptInterpreter.java:114)[129:org.eclipse.smarthome.model.script:0.9.0.b5]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:901)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:864)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:223)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter._doEvaluate(XbaseInterpreter.java:446)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.doEvaluate(XbaseInterpreter.java:227)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.internalEvaluate(XbaseInterpreter.java:203)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.evaluate(XbaseInterpreter.java:189)[145:org.eclipse.xtext.xbase:2.9.2.v20160428-1452]
        at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptImpl.execute(ScriptImpl.java:77)[130:org.eclipse.smarthome.model.script.runtime:0.9.0.b5]
        at org.eclipse.smarthome.model.script.engine.ScriptExecutionThread.run(ScriptExecutionThread.java:42)[129:org.eclipse.smarthome.model.script:0.9.0.b5]
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.domain.tld, port: 465;
  nested exception is:
        java.net.ConnectException: Connection refused (Connection refused)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
        ... 23 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)[:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)[:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)[:1.8.0_131]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)[:1.8.0_131]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[:1.8.0_131]
        at java.net.Socket.connect(Socket.java:589)[:1.8.0_131]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)[:1.8.0_131]
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:205)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
        ... 30 more

```

## Possible Solution

None found, instead of doing some NATing in the firewall. 

## Steps to Reproduce (for bugs)

1. Install Mail Action add-on
2. Create mail.cfg file in services/ directory
3. Add following settings to mail.cfg

```
# The SMTP server hostname, e.g. "smtp.gmail.com"
hostname=smtp.domain.tld

# the SMTP port to use (optional, defaults to 25 (resp. 587 for TLS/SSL))
port=587

# the username and password if the SMTP server requires authentication
username=root@domain.tld
password=password

# The email address to use for sending mails
from=openhab2@domain.tld

# set to "true", if STARTTLS is enabled (not required) for the connection
# (optional, defaults to false)
tls=true

# set to "true", if SSL negotiation should occur on connection
# do not use both tls=true and ssl=true
# (optional, defaults to false)
#ssl=false

# set to "true", if POP before SMTP (another authentication mechanism)
# should be enabled. Username and Password are taken from the above
# configuration (optional, default to false)
#popbeforesmtp=

# Character set used to encode message body
# (optional, if not provided platform default is used)
#charset=
```

## Context

OpenHAB is unable to send mails via my SMTP server, using another SMTP server listing on port is working as expected.

## Your Environment

* Version used: openhab2 2.1(RPI3), mail-action 1.10 (same with OH2.0 and Mail 1.09)
* Operating System and version : OpenHABianPI, daily version, RPI3

**Comment by 9037568** [comment]
Please refer to [this issue](https://github.com/openhab/openhab1-addons/issues/5004) and the associated community forum thread.

Sounds to me like they're probably the same cause.

**Comment by nRaecheR** [comment]
Yes, that's right. My report is a duplicate of that one. Thank you, will follow it there.

**Comment by 9037568** [comment]
Closed as a confirmed duplicate.
