### ISSUE TITLE
[CalDav] Fails for calendar resources containing curly braces

### ISSUE THREAD

**Issue by brunkj** [openhab/openhab1-addons#5272]
The error I get is below. My entry from openhab.cfg is below as well.

################################caldav
caldavio:jason:reloadInterval=1
caldavio:jason:preloadTime=2880
caldavio:jason:oauth=true
caldavio.jason:disableCertificateVerification=false

caldavio:jason:username=<email omitted>@gmail.com
caldavio:jason:password=<password omitted>
caldavio:jason:url=https://www.google.com/calendar/dav/<email omitted>@gmail.com/events
caldavPersonal:usedCalendars=jason

2017-08-04 10:08:27.697 [ERROR] [o.o.i.c.i.job.EventReloaderJob] - error while loading calendar entries: Illegal character in path at index 65: https://www.google.com/calendar/dav/jason.brunk@gmail.com/events/{4913D9DD-6C56-4445-97FE-623E60533DB1}.ics
java.lang.IllegalArgumentException: Illegal character in path at index 65: https://www.google.com/calendar/dav/jason.brunk@gmail.com/events/{4913D9DD-6C56-4445-97FE-623E60533DB1}.ics
at java.net.URI.create(URI.java:852) ~[na:1.8.0_131]
at org.apache.http.client.methods.HttpGet.(HttpGet.java:69) ~[na:na]
at com.github.sardine.impl.SardineImpl.get(SardineImpl.java:745) ~[na:na]
at com.github.sardine.impl.SardineImpl.get(SardineImpl.java:741) ~[na:na]
at com.github.sardine.impl.SardineImpl.get(SardineImpl.java:732) ~[na:na]
at com.github.sardine.impl.SardineImpl.get(SardineImpl.java:145) ~[na:na]
at org.openhab.io.caldav.internal.job.EventReloaderJob.loadEvents(EventReloaderJob.java:314) ~[na:na]
at org.openhab.io.caldav.internal.job.EventReloaderJob.execute(EventReloaderJob.java:135) ~[na:na]
at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-all-2.1.7.jar:na]
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [quartz-all-2.1.7.jar:na]
Caused by: java.net.URISyntaxException: Illegal character in path at index 65: https://www.google.com/calendar/dav/jason.brunk@gmail.com/events/{4913D9DD-6C56-4445-97FE-623E60533DB1}.ics
at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_131]
at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_131]
at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[na:1.8.0_131]
at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_131]
at java.net.URI.(URI.java:588) ~[na:1.8.0_131]
at java.net.URI.create(URI.java:850) ~[na:1.8.0_131]
… 9 common frames omitted

Looks like something to do with the { }

**Comment by 9037568** [comment]
Started as a [thread in the forum](https://community.openhab.org/t/caldev-issues/32688/8).

Apparently some calendar resources can contain curly braces (`{` or `}`). We need to just urlEncode the whole resource.

Fix in progress...

**Comment by brunkj** [comment]
my setup is in place, so if you need me to drop a new jar file i am 100% down to test

**Comment by 9037568** [comment]
Here's a [test jar](https://drive.google.com/open?id=0B8vYheWfObP9akZVcG81dW5XWkU) that should fix the problem.
