### ISSUE TITLE
[mapdb] NPE in org.mapdb.DataOutput2.writeUTF()

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab1-addons#5285]
## Current behavior
log in openHAB 2.1.0 - release build -

```
2017-08-21 12:32:14.893 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl@165b978, netatmoOutdoorTempTrend, null]' about state update of item java.lang.NullPointerException: {}
```

log in openHAB 2.1.0 -  snapshot 1020 -
```
2017-08-21 21:19:47.965 [WARN ] [pse.smarthome.core.items.GenericItem] - failed notifying listener '[org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl@2a31d596, Netatmo_EV_MasterBedroom_Luchtvochtigheid, null]' about state update of item {}: {}
java.lang.NullPointerException: null
	at org.mapdb.DataOutput2.writeUTF(DataOutput2.java:147) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.openhab.persistence.mapdb.internal.MapDBitemSerializer.serialize(MapDBitemSerializer.java:45) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.openhab.persistence.mapdb.internal.MapDBitemSerializer.serialize(MapDBitemSerializer.java:1) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:397) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.BTreeMap$NodeSerializer.serialize(BTreeMap.java:288) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.Store.serialize(Store.java:154) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.StoreWAL.update(StoreWAL.java:371) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.Caches$HashTable.update(Caches.java:270) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.mapdb.BTreeMap.put(BTreeMap.java:643) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.openhab.persistence.mapdb.internal.MapDBPersistenceService.store(MapDBPersistenceService.java:161) [198:org.openhab.persistence.mapdb:1.11.0.201708190109]
	at org.openhab.core.persistence.internal.PersistenceServiceDelegate.store(PersistenceServiceDelegate.java:55) [195:org.openhab.core.compat1x:2.2.0.201708201100]
	at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:119) [103:org.eclipse.smarthome.core.persistence:0.9.0.201708151402]
	at org.eclipse.smarthome.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:420) [103:org.eclipse.smarthome.core.persistence:0.9.0.201708151402]
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:229) [98:org.eclipse.smarthome.core:0.9.0.201708151402]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Related sources
Related discussion in community: https://community.openhab.org/t/what-channel-types-are-supported-by-wich-netatmo-device/24394/28
Related issue in eclipse/smarthome#4104

## Steps to reproduce
Very basic setup to reproduce this error:

**Precondition:**
`mapdb` persistence installed and Item `mapdbString` should have a matching strategy : everyChange.

demo.items
```csv
Switch mapdbSwitch
String mapdbString "[%s]"
```

demo.rules
```php
rule "mapdb Test"
when
    Item mapdbSwitch changed
then
    mapdbString.sendCommand(new StringType(null))
end
```

**Comment by cweitkamp** [comment]
PR #5315
