### ISSUE TITLE
[wol1] Issue with MAC Adress containing "00" 

### ISSUE THREAD

**Issue by felixloesch** [openhab/openhab1-addons#5317]
## Current Behavior

The Wake On LAN Binding 1.11.0-SNAPSHOT seems to have an issue when the configuration contains a "00" in the MAC Adress. I have the following item defined: 

Switch PC   "PC"   (SF_Office)   { wol="192.168.0.255#‎00:1b:21:94:ae:3b" }

and get the following error which is raised due to a NumberFormatException:

2017-10-02 20:33:25.079 [ERROR] [el.item.internal.GenericItemProvider] - Binding configuration of type 'wol' of item 'PC' could not be parsed correctly.
org.eclipse.smarthome.model.item.BindingConfigParseException: Invalid hex digit in MAC address [digit=‎00
        at org.openhab.core.binding.internal.BindingConfigReaderDelegate.processBindingConfiguration(BindingConfigReaderDelegate.java:50) [203:org.openhab.core.compat1x:2.2.0.201709130643]
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:331) [124:org.eclipse.smarthome.model.item:0.9.0.201709121704]
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:303) [124:org.eclipse.smarthome.model.item:0.9.0.201709121704]
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:188) [124:org.eclipse.smarthome.model.item:0.9.0.201709121704]
        at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:366) [124:org.eclipse.smarthome.model.item:0.9.0.201709121704]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:287) [123:org.eclipse.smarthome.model.core:0.9.0.201709121704]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136) [123:org.eclipse.smarthome.model.core:0.9.0.201709121704]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234) [123:org.eclipse.smarthome.model.core:0.9.0.201709121704]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297) [123:org.eclipse.smarthome.model.core:0.9.0.201709121704]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:204) [98:org.eclipse.smarthome.core:0.9.0.201709121704]
        at java.lang.Thread.run(Thread.java:745) [?:?]

## Possible Solution

Use a different method for converting the MAC address to the byte array. The following code should work: 

String macAddress = "AA:BB:CC:DD:EE:FF";
String[] macAddressParts = macAddress.split(":");

// convert hex string to byte values
Byte[] macAddressBytes = new Byte[6];
for(int i=0; i<6; i++){
    Integer hex = Integer.parseInt(macAddressParts[i], 16);
    macAddressBytes[i] = hex.byteValue();
}

In the current code a cast to (byte) is used.

**Comment by 9037568** [comment]
There's no reason parseInt should fail on a value of "00".

When I copied your item binding string and pasted it into a file for testing, I found a bad series of UTF-8 bytes between the "#" and the first "0". (UTF-8 bytes were 0xe2808e, which is not a valid sequence)

You need to edit your item binding to remove any such invalid characters.
