### ISSUE TITLE
[souliss] NullPointerException in receiveCommand

### ISSUE THREAD

**Issue by rymdbullen** [openhab/openhab1-addons#5369]
## Current Behavior
Activating the souliss1 binding, switching on/off any item that is not a souliss item (not a SoulissGenericTypical), causes a NullPointerException: 

```java
2017-11-25 16:00:01.106 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=openhab/command/GF_Living_Ceiling_Switch] {bridgemarker=true, item=GF_Living_Ceiling_Switch, command=OFF} | {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/*, service.pid=org.openhab.souliss, component.name=org.openhab.binding.souliss, component.id=209, service.id=331, service.bundleid=212, service.scope=bundle} | Bundle(org.openhab.binding.souliss_1.11.0.201711190210 [212])]
java.lang.NullPointerException: null
        at org.openhab.binding.souliss.internal.SoulissBinding.receiveCommand(SoulissBinding.java:135) [212:org.openhab.binding.souliss:1.11.0.201711190210]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) [208:org.openhab.core.compat1x:2.2.0.201711231443]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.run(HandlerTask.java:70) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Expected Behavior
No stacktrace as the item should not be handled by the Souliss binding.

## Possible Solution
Add a conditional catching the null variable? Pull request is in the pipe.

## Context
For me, this happens in the latest release 1093

## Your Environment
* Version used: openHAB 2.2.0 Build #1093, online version.

**Comment by rymdbullen** [comment]
PR created: https://github.com/rymdbullen/openhab1-addons/tree/5369-souliss-fix-npe
