### ISSUE TITLE
[anel] Anel Hut 6.1 (or 6.2) Wrong password message not supported

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab1-addons#5379]
## Expected Behavior
When I call an AnelHut with a wrong password, I want openhab to understand the message.

## Current Behavior
When I call an anelhut, with a wrong password, I see this in the log file

07:50:28.158 [ERROR] [ng.anel.internal.AnelConnectorThread] - Error occured when received data from Anel device: 192.168.1.144
java.lang.IllegalArgumentException: Data with 16 or at least 26 values expected but 4 received: NET-PwrCtrl:ANEL44         :NoPass:Err
	at org.openhab.binding.anel.internal.AnelDataParser.parseData(AnelDataParser.java:92)[221:org.openhab.binding.anel:1.11.0.201711141001]
	at org.openhab.binding.anel.internal.AnelConnectorThread.run(AnelConnectorThread.java:254)[221:org.openhab.binding.anel:1.11.0.201711141001]

## Possible Solution

I assume that an answer with 4 values received should be allowed and correctly parsed. 

## Steps to Reproduce (for bugs)
Change the password on a hut, call the hut from openhab. 

## Your Environment
* Version used: openHAB 2.2.0 Build #1003
* Version used: AnelHUT 6.1 or 6.2

**Comment by yveshanoulle** [comment]
mm for me this is a bug and not an enhancement. When there is a wrong password supplied, the situation is not dealt well.

**Comment by paphko** [comment]
I agree that this is an enhancement because we cannot handle *all* possible responses without knowing them. In this respect, the current behavior looks ok to me; maybe the message could additionally say that the user should check the response for hints what could be wrong.
However, for the case of a wrong password we should add a dedicated error messase.

As soon as I find some time, I'll create a PR for this.
