### ISSUE TITLE
[HTTP] NPE while executing background thread HTTP Refresh Service

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab1-addons#5388]
This NPE occured while shutting down OH2.

```
...
2017-12-18 15:06:36.288 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread HTTP Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:213) [228:org.openhab.binding.http:1.11.0]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) [233:org.openhab.core.compat1x:2.2.0]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [233:org.openhab.core.compat1x:2.2.0]
...
2017-12-18 15:06:39.328 [INFO ] [b.core.service.AbstractActiveService] - HTTP Refresh Service has been shut down
...
```

**Comment by 9037568** [comment]
I [implemented a check](https://github.com/openhab/openhab1-addons/compare/master...9037568:http?expand=1) so that we ignore calls to execute() after deactivate() has been called.

Could you try out this [test jar](https://drive.google.com/open?id=17P_CGUVnWw1OyHeKfrEra-e-yqfC5VqN) and let me know the results?

Thanks!

**Comment by cweitkamp** [comment]
I will do that. It will be a little bit tricky because the refresh has to be executed exactly while shutting down of OH2 - but it should be reproducible with a very small refresh interval.

**Comment by cweitkamp** [comment]
I put together a similar setup in my development environment. I used one HTTP cache item - refreshing every 10 ms - and two items related to it. After three OH2 restarts I reproduced the reported NPE with the old binding version (1.11.0). I exchanged the binding with your new version (1.12.0.201712250333) and began to restart OH2 again. After approximately five trials I saw the same NPE in my log files:
```
2018-01-07 16:10:14.231 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread HTTP Refresh Service
java.lang.NullPointerException: null
        at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:227) [244:org.openhab.binding.http:1.12.0.201712250333]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) [250:org.openhab.core.compat1x:2.2.0]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [250:org.openhab.core.compat1x:2.2.0]
```
The added debug message was never logged.

**Comment by 9037568** [comment]
Wonder if we're now dealing with a race between the call to deactivate() and the call to execute()...

Does the log show them occurring at the same time?

**Comment by cweitkamp** [comment]
> Wonder if we're now dealing with a race between the call to deactivate() and the call to execute()...

Yes, I guess that too.

> Does the log show them occurring at the same time?

I am going to append a longer log tonight. Additionally I am going to pull your changes and add two additional debug logs at the beginning of the `execute()` and `deactivate()` methods to keep track of the execution order of them. Keep you posted.

**Comment by cweitkamp** [comment]
Here it is. I used [this code](https://github.com/openhab/openhab1-addons/compare/master...cweitkamp:http?expand=1).
```
2018-01-08 21:23:23.644 [DEBUG] [ab.binding.http.internal.HttpBinding] - Calling 'execute()' ...
2018-01-08 21:23:23.652 [DEBUG] [ab.binding.http.internal.HttpBinding] - item 'hueLivingRoomTemperature' is fetched from cache
2018-01-08 21:23:23.655 [DEBUG] [ab.binding.http.internal.HttpBinding] - updating cache for 'hueLivingRoomMotionSensorTemperature' ('http://hue-bridge/api/XXXXXX/sensors/11')
2018-01-08 21:23:24.947 [DEBUG] [org.openhab.binding.http            ] - ServiceEvent UNREGISTERING - {org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler}={event.topics=openhab/*, service.pid=org.openhab.http, component.name=org.openhab.binding.http, component.id=13, service.id=319, service.bundleid=252, service.scope=bundle} - org.openhab.binding.http
2018-01-08 21:23:24.951 [DEBUG] [ab.binding.http.internal.HttpBinding] - Calling 'deactivate()' ...
2018-01-08 21:23:24.990 [DEBUG] [org.openhab.binding.http            ] - ServiceEvent UNREGISTERING - {org.openhab.model.item.binding.BindingConfigReader, org.openhab.binding.http.HttpBindingProvider}={component.name=org.openhab.binding.http.genericbindingprovider, component.id=12, service.id=118, service.bundleid=252, service.scope=bundle} - org.openhab.binding.http
2018-01-08 21:23:25.001 [DEBUG] [org.openhab.binding.http            ] - BundleEvent STOPPING - org.openhab.binding.http
2018-01-08 21:23:25.014 [DEBUG] [.binding.http.internal.HttpActivator] - HTTP binding has been stopped.
2018-01-08 21:23:25.022 [DEBUG] [org.openhab.binding.http            ] - BundleEvent STOPPED - org.openhab.binding.http
2018-01-08 21:23:25.029 [DEBUG] [org.openhab.binding.http            ] - BundleEvent UNRESOLVED - org.openhab.binding.http
2018-01-08 21:23:25.075 [DEBUG] [org.openhab.binding.http            ] - BundleEvent UNINSTALLED - org.openhab.binding.http
2018-01-08 21:23:27.639 [DEBUG] [ab.binding.http.internal.HttpBinding] - transformed response is '18.81'
2018-01-08 21:23:27.647 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread HTTP Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:229) [252:org.openhab.binding.http:1.12.0.201801082003]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) [250:org.openhab.core.compat1x:2.2.0]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [250:org.openhab.core.compat1x:2.2.0]
2018-01-08 21:23:28.652 [INFO ] [b.core.service.AbstractActiveService] - HTTP Refresh Service has been shut down
```

**Comment by 9037568** [comment]
So based on that, it appears we need a mutex to prevent these two methods from running simultaneously. Like [this](https://github.com/openhab/openhab1-addons/compare/master...9037568:http?expand=1).

I incorporated your changes also.

**Comment by cweitkamp** [comment]
Hi @9037568,

sry for my late response. I lost track of this. Few days ago I got a reminder that it is still present. I did some more tests with your latest changes and it was not possible for me to reproduce the NPE. Shall we create a PR for it?

```
2018-10-30 21:30:52.060 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread HTTP Refresh Service
java.lang.NullPointerException: null
        at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:213) ~[?:?]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) ~[231:org.openhab.core.compat1x:2.4.0.M5]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [231:org.openhab.core.compat1x:2.4.0.M5]
...
2018-10-30 21:30:53.096 [INFO ] [b.core.service.AbstractActiveService] - HTTP Refresh Service has been shut down
...
```

**Comment by 9037568** [comment]
Thanks, @cweitkamp . Care to review the PR or retest the fix?

**Comment by cweitkamp** [comment]
The code looks good. I try to test it in the next few days. Currently I removed the HTTP binding completely from my live environment which forces me to setup a test scenario for this.
