### ISSUE TITLE
OH2.2.0-1 KNXnet/IP Tunneling response timeout waiting for confirmation

### ISSUE THREAD

**Issue by starranger3** [openhab/openhab1-addons#5399]
**OH2.2.0-1 KNXnet/IP Tunneling response timeout waiting for confirmation**
I have installed openHAB 2.2.0-1 on my raspberry pi 3 and activated the knx binding. The installation was so far successfull and i can control lights and shutter via the basic ui over the knx bus. However, the reaction is very slow and it takes almost 2-3 seconds till a light is activated or deactivated. I get a lot of warnings on the console, see attached trace dump for the knx address 3/1/1.
I am using a MDT KNX IP Interace in TUNNEL mode, since the IP interface does not support ROUTER mode.

**Trace:**
2017-12-30 11:50:53.369 [vent.ItemStateChangedEvent] - TIstEGWohnen changed from 19.52 to 19.45

==> /var/log/openhab2/openhab.log <==
2017-12-30 11:50:56.371 [WARN ] [.binding.knx.internal.bus.KNXBinding] - Value '19.45' could not be sent to the KNX bus using datapoint 'command DP 3/1/1 TIstEGWohnen, DPT main 0 id 9.001, low priority' - retrying one time: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99
2017-12-30 11:50:56.371 [WARN ] [tuwien.auto.calimero ] - KNXnet/IP Tunneling 192.168.2.100:3671: response timeout waiting for confirmation
tuwien.auto.calimero.exception.KNXTimeoutException: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99
at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:236) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:269) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:149) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:263) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:304) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:240) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:466) [206:org.openhab.binding.knx:1.11.0]
at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:438) [206:org.openhab.binding.knx:1.11.0]
at org.openhab.binding.knx.internal.bus.KNXBinding.writeToKNX(KNXBinding.java:149) [206:org.openhab.binding.knx:1.11.0]
at org.openhab.binding.knx.internal.bus.KNXBinding.internalReceiveUpdate(KNXBinding.java:126) [206:org.openhab.binding.knx:1.11.0]
at org.openhab.core.binding.AbstractBinding.receiveUpdate(AbstractBinding.java:113) [207:org.openhab.core.compat1x:2.2.0]
at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:39) [207:org.openhab.core.compat1x:2.2.0]
at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
at java.lang.Thread.run(Thread.java:748) [?:?]
2017-12-30 11:50:59.383 [ERROR] [.binding.knx.internal.bus.KNXBinding] - Value '19.45' could not be sent to the KNX bus using datapoint 'command DP 3/1/1 TIstEGWohnen, DPT main 0 id 9.001, low priority' - giving up after second try: no confirmation reply received for L-Data.req from 1.1.240 to 3/1/1, low priority hop count 6 repeat tpdu 00 80 07 99

**The corresponding entry in the items file:**

//--> Heizung [3/x/x]
//================================================================
//--> EG Wohnen [3/1/x]
Number TIstEGWohnen "EG Wohnen Temperatur Ist [%.1f °C]" (gWohnenEG, gTemp) {knx = "<3/1/1"}

**The corresponding entry in the /etc/openhab2/services/knx.cfg:**
ip=192.168.2.100
busaddr=1.1.240
ignorelocalevents=true
type=TUNNEL
port=3671

**The corresponding entry in the /etc/default/knxd:**
KNXD_OPTIONS="--eibaddr=1.1.240 --client-addrs=1.1.129:8 -d -D -T -R -S -i --listen-local=/tmp/knx -b ipt:192.168.2.100"

**Comment by hefn** [comment]
Hello!
If you select in knx.cfg the ip=192.168.2.100, and this is the IP of your KNX IP interface, and you want to use it in tunnel mode, you do not need knxd. OH2 communicates via calimero directly to the KNX IP interface. I prefer this way. Disable knxd starting and give it a try. You probably also should restart  your knx ip interface when it works in tunnel mode before enabling the connection via OH2 and calimero (check the log file after starting OH2).

The other way, which i would not recommend, is to use knx.cfg in router mode, change there the local ip where knxd runs. knxd runs in router mode to OH2 and enables the communication to your knx ip interface via tunneling.

What you cannot solve with any of these ways is the telegram echo problem described in "[KNX] binding in OpenHAB2 generates lots of bus traffic #4547", but e.g. lights on/off etc. should work with very short delay.
Regards

**Comment by starranger3** [comment]
Hi,
thanks for the hint! I disabled the knxd and restartet OH2. The lights are switched on and off in a reasonable time but still sometimes I need to wait 1-2 seconds if the actions is performed. The delay happens always if there are at the same time on the bus some echo messages going on.

When I switch off the lights for example, I get the following echo messages, which I think is related to issue  [#4547"](https://github.com/openhab/openhab1-addons/issues/4547 )

==> /var/log/openhab2/events.log <==
2018-01-03 23:04:32.331 [ome.event.ItemCommandEvent] - Item 'BelDGKind' received command OFF
2018-01-03 23:04:32.409 [vent.ItemStateChangedEvent] - BelDGKind changed from ON to OFF

==> /var/log/openhab2/openhab.log <==
2018-01-03 23:04:35.337 [WARN ] [.binding.knx.internal.bus.KNXBinding] - Value 'OFF' could not be sent to the KNX bus using datapoint 'command DP 1/0/1 BelDGKind, DPT main 0 id 1.001, low priority' - retrying one time: no confirmation reply received for L-Data.req from 1.1.240 to 1/0/1, low priority hop count 6 repeat tpdu 00 80
2018-01-03 23:04:35.339 [WARN ] [tuwien.auto.calimero                ] - KNXnet/IP Tunneling 192.168.2.100:3671: response timeout waiting for confirmation
tuwien.auto.calimero.exception.KNXTimeoutException: no confirmation reply received for L-Data.req from 1.1.240 to 1/0/1, low priority hop count 6 repeat tpdu 00 80
        at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:236) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:269) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:149) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:263) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:304) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:240) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:466) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:438) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.writeToKNX(KNXBinding.java:149) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.internalReceiveCommand(KNXBinding.java:112) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:94) [216:org.openhab.core.compat1x:2.2.0]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) [216:org.openhab.core.compat1x:2.2.0]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-01-03 23:04:38.358 [ERROR] [.binding.knx.internal.bus.KNXBinding] - Value 'OFF' could not be sent to the KNX bus using datapoint 'command DP 1/0/1 BelDGKind, DPT main 0 id 1.001, low priority' - giving up after second try: no confirmation reply received for L-Data.req from 1.1.240 to 1/0/1, low priority hop count 6 repeat tpdu 00 80
2018-01-03 23:04:38.360 [WARN ] [tuwien.auto.calimero                ] - KNXnet/IP Tunneling 192.168.2.100:3671: response timeout waiting for confirmation
tuwien.auto.calimero.exception.KNXTimeoutException: no confirmation reply received for L-Data.req from 1.1.240 to 1/0/1, low priority hop count 6 repeat tpdu 00 80
        at tuwien.auto.calimero.knxnetip.ClientConnection.doExtraBlockingModes(ClientConnection.java:236) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.ConnectionBase.send(ConnectionBase.java:269) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.send(KNXnetIPTunnel.java:149) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.onSend(KNXNetworkLinkIP.java:263) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.AbstractLink.send(AbstractLink.java:304) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.link.KNXNetworkLinkIP.sendRequestWait(KNXNetworkLinkIP.java:240) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:466) [215:org.openhab.binding.knx:1.11.0]
        at tuwien.auto.calimero.process.ProcessCommunicatorImpl.write(ProcessCommunicatorImpl.java:438) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.writeToKNX(KNXBinding.java:158) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.binding.knx.internal.bus.KNXBinding.internalReceiveCommand(KNXBinding.java:112) [215:org.openhab.binding.knx:1.11.0]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:94) [216:org.openhab.core.compat1x:2.2.0]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) [216:org.openhab.core.compat1x:2.2.0]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.1.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.ru

**Comment by GoldenEyeCF** [comment]
I face the same issue after the connection loss described here : https://community.openhab.org/t/regular-knx-link-loss-since-upgrade-to-2-2/37658

**Comment by starranger3** [comment]
Closed, everything now working fine, for solution, see [[KNX] binding in OpenHAB2 generates lots of bus traffic #4547](https://github.com/openhab/openhab1-addons/issues/4547)
