### ISSUE TITLE
[homematic] Can't convert BOOL value '0' with OnOffTypeConverter 

### ISSUE THREAD

**Issue by tbail** [openhab/openhab1-addons#5436]
Since Build 1177 of OH 2.3 i get the above error in the log. Following is a snippet from the log.

```
2018-01-11 09:36:25.224 [ERROR] [ematic.handler.HomematicThingHandler] - Can't convert BOOL value '0' with OnOffTypeConverter for 'LEQxxxxx:0#LOWBAT'
org.openhab.binding.homematic.internal.converter.ConverterTypeException: Can't convert BOOL value '0' with OnOffTypeConverter for 'LEQxxxxx:0#LOWBAT'
        at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertFromBinding(AbstractTypeConverter.java:114) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:250) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:226) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:233) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$0(AbstractHomematicGateway.java:615) ~[214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:61) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:612) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:94) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:47) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:64) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at org.openhab.binding.homematic.internal.communicator.server.BinRpcResponseHandler.run(BinRpcResponseHandler.java:46) [214:org.openhab.binding.homematic:2.3.0.201801092213]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

The error is confirmed by two other users in the forum and is in build 1182 still available

**Comment by tbail** [comment]
It is not the the openhab 1 addon -> Moved it to the right area
