### ISSUE TITLE
[pilight] items in openhab are not updated when pilight item changes

### ISSUE THREAD

**Issue by darkcheater** [openhab/openhab1-addons#5459]
## Expected Behavior
When a pilight item changes (through received signal from 433 Mhz remote or from pilight webgui) I expect the declared switch item in OpenHab to update accordingly.

## Current Behavior
OpenHab item does not change when pilight item changes (checked via pilight webgui). I think the connection between OpenHab and pilight is just completely broken.

I get the following exceptions in openhab.log
```
2018-01-25 17:27:31.605 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:rpi item Wohnzimmer_Stehlampe_pilight bound to device Stehlampe

2018-01-25 17:27:31.629 [ERROR] [org.openhab.binding.pilight ] - [org.openhab.binding.pilight.binding(231)] The addBindingProvider method has thrown an exception
java.lang.NullPointerException: null
	at org.openhab.binding.pilight.internal.PilightBinding.checkItemState(PilightBinding.java:401) [242:org.openhab.binding.pilight:1.9.0.201609090111]

	at org.openhab.binding.pilight.internal.PilightBinding.allBindingsChanged(PilightBinding.java:379) [242:org.openhab.binding.pilight:1.9.0.201609090111]

	at org.openhab.core.binding.AbstractBinding.addBindingProvider(AbstractBinding.java:61) [200:org.openhab.core.compat1x:2.2.0]

	at org.openhab.binding.pilight.internal.PilightBinding.addBindingProvider(PilightBinding.java:241) [242:org.openhab.binding.pilight:1.9.0.201609090111]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.apache.felix.scr.impl.inject.BaseMethod.invokeMethod(BaseMethod.java:229) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.inject.BaseMethod.access$500(BaseMethod.java:39) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.inject.BaseMethod$Resolved.invoke(BaseMethod.java:650) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.inject.BaseMethod.invoke(BaseMethod.java:506) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.inject.BindMethod.invoke(BindMethod.java:658) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:1722) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.DependencyManager.open(DependencyManager.java:1556) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:261) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:109) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823) [42:org.apache.felix.scr:2.0.12]

	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [?:?]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619) [?:?]

	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39) [15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]

	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [?:?]

	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [?:?]

	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [?:?]

	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [?:?]

	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [?:?]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:291) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1215) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1136) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:945) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:881) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1167) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:127) [42:org.apache.felix.scr:2.0.12]

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [?:?]

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [?:?]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:887) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:874) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:132) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:941) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:741) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:675) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:430) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:390) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:265) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:254) [42:org.apache.felix.scr:2.0.12]

	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:227) [42:org.apache.felix.scr:2.0.12]

	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) [?:?]

	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) [?:?]

	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [?:?]

	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [?:?]

	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213) [?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120) [?:?]

	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112) [?:?]

	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:156) [?:?]

	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) [?:?]

	at org.eclipse.osgi.container.Module.start(Module.java:467) [?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1600) [?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

pilight log shows:
```
[Jan 25 17:27:32:581993] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:27:32:591632] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:27:42:645699] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:27:52:648250] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:27:52:648361] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:02:651991] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:02:652105] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:12:654019] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:12:654085] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:22:655864] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:32:658244] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 25 17:28:32:658310] pilight-daemon: WARNING: (webserver) could not read (null)
```

## Possible Solution
Fix connection between OpenHab and pilight.

## Context
I want to control my 433 Mhz plugs from OpenHab.
As my wife is using the usual remote control, I have to keep track of the states via pilight-receive in order to toggle the items correctly.

## Your Environment
OpenHab 2.2 running on Raspberry Pi 3 under openhabianPi.
Latest pilight (8.0.9)
pilight binding 1.9.0 snapshot and 1.12.0 snapshot tested.
OpenHab pilight.cfg:

```
# IP address of the pilight daemon
pilight:rpi.host=localhost
#
# Port of the pilight daemon
pilight:rpi.port=5001
#
# Optional delay (in millisecond) between consecutive commands.
# Recommended value without band pass filter: 1000
# Recommended value with band pass filter: somewhere between 200-500
pilight:rpi.delay=1000
```

**Comment by 9037568** [comment]
Guessing this is a configuration problem.

Try dropping the `pilight:` from your pilight.cfg:

````
# IP address of the pilight daemon
rpi.host=localhost
#
# Port of the pilight daemon
rpi.port=5001
#
# Optional delay (in millisecond) between consecutive commands.
# Recommended value without band pass filter: 1000
# Recommended value with band pass filter: somewhere between 200-500
rpi.delay=1000
````

**Comment by darkcheater** [comment]
Unfortunately this was not the problem :(
The pilight log entry repeats every 10 seconds:
```
[Jan 26 07:48:21:618679] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:21:620791] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:31:620423] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:31:627591] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:41:622411] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:41:629946] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:51:624821] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:48:51:632119] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:01:626804] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:01:634227] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:11:628711] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:11:636335] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:21:631217] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:21:638423] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:31:633222] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:31:640611] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:41:635404] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:41:642989] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:51:642436] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:49:51:649583] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:50:01:644764] pilight-daemon: WARNING: (webserver) could not read (null)
[Jan 26 07:50:01:652210] pilight-daemon: WARNING: (webserver) could not read (null)
```

**Comment by 9037568** [comment]
To do any useful troubleshooting, a debug log will be needed.

**Comment by darkcheater** [comment]
I managed to change the log level and here is the result:
```
2018-01-27 08:44:09.758 [DEBUG] [ng.pilight.internal.PilightActivator] - pilight binding has been started.

2018-01-27 08:44:09.763 [DEBUG] [org.openhab.binding.pilight ] - BundleEvent STARTED - org.openhab.binding.pilight

2018-01-27 08:44:09.795 [DEBUG] [org.openhab.binding.pilight ] - ServiceEvent REGISTERED - {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/command/*, service.pid=org.openhab.pilight, component.name=org.openhab.binding.pilight.binding, component.id=232, service.id=363, service.bundleid=245, service.scope=bundle} - org.openhab.binding.pilight

2018-01-27 08:44:09.843 [DEBUG] [ding.pilight.internal.PilightBinding] - All bindings changed

2018-01-27 08:44:09.852 [DEBUG] [org.openhab.binding.pilight ] - ServiceEvent REGISTERED - {org.openhab.model.item.binding.BindingConfigReader, org.openhab.binding.pilight.PilightBindingProvider}={component.name=org.openhab.binding.pilight.genericbindingprovider, component.id=233, service.id=362, service.bundleid=245, service.scope=bundle} - org.openhab.binding.pilight

2018-01-27 08:44:09.863 [INFO ] [ternal.PilightGenericBindingProvider] - pilight:rpi item Wohnzimmer_Stehlampe_pilight bound to device Stehlampe

2018-01-27 08:44:09.868 [DEBUG] [ding.pilight.internal.PilightBinding] - Binding changed for item Wohnzimmer_Stehlampe_pilight

2018-01-27 08:44:12.037 [DEBUG] [ding.pilight.internal.PilightBinding] - All bindings changed

2018-01-27 08:44:12.037 [DEBUG] [ng.pilight.internal.PilightConnector] - pilight reconnecting

2018-01-27 08:44:12.056 [DEBUG] [ding.pilight.internal.PilightBinding] - All bindings changed

2018-01-27 08:44:12.056 [DEBUG] [ng.pilight.internal.PilightConnector] - pilight reconnecting

2018-01-27 08:44:12.411 [DEBUG] [ng.pilight.internal.PilightConnector] - Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

at [Source: java.net.SocketInputStream@1eaf76d; line: 1, column: 2]

org.codehaus.jackson.JsonParseException: Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

at [Source: java.net.SocketInputStream@1eaf76d; line: 1, column: 2]

	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900) [200:org.openhab.core.compat1x:2.2.0]

	at org.openhab.binding.pilight.internal.PilightConnector.reconnect(PilightConnector.java:227) [245:org.openhab.binding.pilight:1.12.0.201801210210]

	at org.openhab.binding.pilight.internal.PilightConnector.run(PilightConnector.java:84) [245:org.openhab.binding.pilight:1.12.0.201801210210]

2018-01-27 08:44:12.411 [DEBUG] [ng.pilight.internal.PilightConnector] - Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

at [Source: java.net.SocketInputStream@927f07; line: 1, column: 2]

org.codehaus.jackson.JsonParseException: Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

at [Source: java.net.SocketInputStream@927f07; line: 1, column: 2]

	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709) [200:org.openhab.core.compat1x:2.2.0]

	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900) [200:org.openhab.core.compat1x:2.2.0]

	at org.openhab.binding.pilight.internal.PilightConnector.reconnect(PilightConnector.java:227) [245:org.openhab.binding.pilight:1.12.0.201801210210]

	at org.openhab.binding.pilight.internal.PilightConnector.run(PilightConnector.java:84) [245:org.openhab.binding.pilight:1.12.0.201801210210]

2018-01-27 08:44:12.429 [DEBUG] [ng.pilight.internal.PilightConnector] - pilight reconnecting

2018-01-27 08:44:12.434 [DEBUG] [ng.pilight.internal.PilightConnector] - pilight reconnecting

```

**Comment by 9037568** [comment]
So now we see that:
a) Your config was the problem.
b) Pilight would appear to be sending data that the binding doesn't expect.

Now you need to figure out what pilight is sending here:
>org.codehaus.jackson.JsonParseException: Unexpected character ('H' (code 72)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

I'd suggest starting a thread in the [community forum](http://community.openhab.org) to see if there are other pilight users that can help you with that.

**Comment by darkcheater** [comment]
I started a thread in the community forum, here is the link:
https://community.openhab.org/t/pilight-binding-how-to-get-it-to-work-with-latest-openhab/39322
If anyone has an idea, feel free to comment.
Thanks!

**Comment by darkcheater** [comment]
Issue was solved by me and described in the community thread.
Problem was the missing port declaration in the pilight config!
