### ISSUE TITLE
[KNX] ft12 connection is not working

### ISSUE THREAD

**Issue by petero-dk** [openhab/openhab1-addons#5494]
[knx] for the KNX add, when using a ft12 serial device directly with OpenHAB the connection fails. 

The errors makes it seem like a problem with the serial port, which meant I did a whole lot of troubleshooting. I compiled the baos examples that communicates via ft12 and they show a working connection. I have other serial ports which works with openhab. All serial ports are configured the same regarding permissions. 

KNXD works with the device. 

## Expected Behavior
A live connection to the KNX bus

## Current Behavior
Failed connection:

```
018-02-13 13:30:58.337 [ERROR] [nx.internal.connection.KNXConnection] - Error connecting to KNX bus: Serial port '/dev/ttyAMA0' could not be opened. Available ports are:
/dev/ttyAMA0
2018-02-13 13:30:58.325 [WARN ] [tuwien.auto.calimero                ] - FT1.2 /dev/ttyAMA0: rxtx serial port access failed
java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:?]
	at tuwien.auto.calimero.serial.FT12Connection.createAdapter(FT12Connection.java:488) [222:org.openhab.binding.knx:1.11.0]
	at tuwien.auto.calimero.serial.FT12Connection.open(FT12Connection.java:425) [222:org.openhab.binding.knx:1.11.0]
	at tuwien.auto.calimero.serial.FT12Connection.<init>(FT12Connection.java:217) [222:org.openhab.binding.knx:1.11.0]
	at tuwien.auto.calimero.serial.FT12Connection.<init>(FT12Connection.java:192) [222:org.openhab.binding.knx:1.11.0]
	at tuwien.auto.calimero.link.KNXNetworkLinkFT12.<init>(KNXNetworkLinkFT12.java:75) [222:org.openhab.binding.knx:1.11.0]
	at org.openhab.binding.knx.internal.connection.KNXConnection.connectBySerial(KNXConnection.java:300) [222:org.openhab.binding.knx:1.11.0]
	at org.openhab.binding.knx.internal.connection.KNXConnection.connect(KNXConnection.java:181) [222:org.openhab.binding.knx:1.11.0]
	at org.openhab.binding.knx.internal.connection.KNXConnection.updated(KNXConnection.java:448) [222:org.openhab.binding.knx:1.11.0]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1479) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1435) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141) [7:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109) [7:org.apache.felix.configadmin:1.8.16]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Possible Solution
It seems that the calls to the RXTX library has changed with a new version and the ft12 part was not the same

## Steps to Reproduce (for bugs)
1. Install OpenHabian
2. Follow all guides to enable Serial Communication
3. (test that the serial device works)
4. Add the serial device to the knx.cfg file, and watch as it errors in the logs.

## Your Environment
* Version used: OpenHab2.2 KNX from the marketplace
* Operating System and version OpenHabian latest

**Comment by petero-dk** [comment]
I am closing this as the KNX2 addon is released and I was on OpenHab 2 with KNX1. Also I have come to realize that my device was using an unsupported mode (cEMI) and proprietary mode switching commands.
