### ISSUE TITLE
[MQTT] Setting QOS results in an error

### ISSUE THREAD

**Issue by CRASH-Tech** [openhab/openhab1-addons#5553]
mqtt.conf
```
openhabian.url=tcp://127.0.0.1:1883
openhabian.clientId=OpenHAB
openhabian.user=username
openhabian.pwd=***
openhabian.qos=1
openhabian.retain=true
openhabian.async=true
```

Log
```
2018-04-14 19:31:19.650 [ERROR] [org.apache.felix.configadmin        ] - [org.openhab.io.transport.mqtt.MqttService, org.osgi.service.cm.ManagedService, id=313, bundle=213/mvn:org.openhab.io/org.openhab.io.transport.mqtt/1.11.0]: Unexpected problem updating configuration org.openhab.mqtt
java.lang.NumberFormatException: For input string: "<qos>"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:580) [?:?]
        at java.lang.Integer.parseInt(Integer.java:615) [?:?]
        at org.openhab.io.transport.mqtt.MqttService.updated(MqttService.java:88) [213:org.openhab.io.transport.mqtt:1.11.0]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1479) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1435) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141) [7:org.apache.felix.configadmin:1.8.16]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109) [7:org.apache.felix.configadmin:1.8.16]
```

**Comment by 9037568** [comment]
Looks like you copied this line from the docs? The fix is just change `<qos>` to a valid value.

````
mqtt:<broker>.qos=<qos>
````

**Comment by 9037568** [comment]
The code should handle this better, even so. I'll submit a PR later.
