### ISSUE TITLE
[Nikobus] In OH2, automatic refresh (module status query) is not working

### ISSUE THREAD

**Issue by DaanDW** [openhab/openhab1-addons#5600]
The automatic refresh (module status query) of the Nikobus binding (1.x binding) is not working in OH2.

My Nikobus binding is working fine but the scheduled refreshed don’t work.

- When I press a Nikobus button, the light reacts and the matching switch Item in Openhab changes -> OK
- When I press a Openhab (nikobus) Item (on my phone app or webinterface), the lights react (Nikobus output reacts) -> OK
- NO automatic refreshes of the Nikobus modules -> NOK

I see this same issue in the community but is seems not yet reported as a bug.
https://community.openhab.org/t/nikobus-compativbility-oh2/7096/73
https://community.openhab.org/t/nikobus-binding-not-updating-status-in-oh2/15761/12

Some people uninstall and reinstall the binding and claims that is works from that on but this don't work for me.

I ported my config from openhab 1.8.3 to 2.3.0, in the 1.8.3 version the automatic module status query works fine but in the 2.3.0 version it don't.

These automatic module status query is a needed function to keep openhab synchronised with the Nikobus installation. Now I have wrong item states in openhab when Nikobus perform automatic functions like a "automatic delayed off" function or "presence simulation" function.
When Openhab and Nikobus are not synchronised, openhab will unwanted change Nikobus output states. Openhab pushes 6 output states at once to the Nikobus installation and forces these outputs to the openhab state, even if this openhab state is not equal to the Nikobus output state. This give unwanted status changes on the Nikobus installation.

I got this out of my LOG:

```
2018-06-05 21:16:01.798 [ERROR] [ding.nikobus.internal.NikobusBinding] - Error occurred during scheduled status refresh.
java.util.concurrent.TimeoutException: No ACK received within timeout and retry count.
	at org.openhab.binding.nikobus.internal.core.NikobusAckMonitor.waitForAck(NikobusAckMonitor.java:92) [232:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding.sendCommand(NikobusBinding.java:155) [232:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding$2.run(NikobusBinding.java:288) [232:org.openhab.binding.nikobus:1.12.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
My openhab 2.3.0 installation is running on a raspberry pi 3 model B, with raspbian lite (stretch).

**Comment by 9037568** [comment]
I'd suggest first increasing the timeout and/or retry count.

If that doesn't work, please put the binding into TRACE mode and capture a log of the problem, then attach it here.

**Comment by DaanDW** [comment]
Is this something that I can do myself to test this as a possible solution?
Or needs the binding to be modified first?

**Comment by 9037568** [comment]
Not sure about the first part (modifying the timeouts). I have assumed they're configurable, but I haven't checked the README. If they're not configurable, you're stuck with just doing the second part (TRACE logs).

**Comment by DaanDW** [comment]
No, you only can configure the COM port, the refresh time (for the automatic status query) and a path setting for the cache (that last one, I use the default = not configurated).

**Comment by ahnidrum** [comment]
I have the same problem after updating to the vesion OH2.3.
Is there a solution or setting for this?

**Comment by DaanDW** [comment]
I don't see a solution that can be done by the end user (like myself).
Therefore I created this issue but I don't know what the next steps are.
It seems that for now there is no movement in this issue and I don't know how to get it started

**Comment by 9037568** [comment]
The next step is to provide the TRACE logs. See [this community forum topic](https://community.openhab.org/t/taming-openhab-2-logging/13976) if you need help setting logging up.

**Comment by bloodybeet** [comment]
Just to let you know - ALL current Nikobus users have this problem, including me. At some point I'll probably be looking into fixing this, I just haven't found the time yet to set up an OpenHab dev environment :(

**Comment by janssen-bart** [comment]
Do you only need TRACE log from nikobus component? 
```
Received: #N961626
2018-12-08 00:44:17.380 [TRACE] [kobus.internal.core.NikobusInterface] - Received: #N9
2018-12-08 00:44:17.405 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 61626
2018-12-08 00:44:17.490 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#N961626, repeats=2]
2018-12-08 00:44:17.494 [TRACE] [nding.nikobus.internal.config.Button] - Processing command #N961626
2018-12-08 00:44:17.494 [TRACE] [ding.nikobus.internal.NikobusBinding] - Sending command with ack $101266444853D1
2018-12-08 00:44:17.497 [TRACE] [s.internal.core.NikobusCommandSender] - Sending command $101266444853D1
2018-12-08 00:44:17.496 [TRACE] [ding.nikobus.internal.NikobusBinding] - Sending status update to PB_GF_Keuken_LB : ON
2018-12-08 00:44:17.499 [DEBUG] [kobus.internal.core.NikobusInterface] - Sending : $101266444853D1
2018-12-08 00:44:17.540 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$0512, repeats=1]
2018-12-08 00:44:17.540 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $0512
2018-12-08 00:44:17.544 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $0512
2018-12-08 00:44:18.084 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $1C664400FF
2018-12-08 00:44:18.109 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 000000000017DD1
2018-12-08 00:44:18.134 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$1C664400FF000000000017DD1B, repeats=1]
2018-12-08 00:44:18.134 [TRACE] [kobus.internal.core.NikobusInterface] - Received: B
2018-12-08 00:44:18.137 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $1C664400FF000000000017DD1B
2018-12-08 00:44:18.140 [TRACE] [obus.internal.core.NikobusAckMonitor] - Received expected ack '$1C664400FF000000000017DD1B'
2018-12-08 00:44:19.348 [TRACE] [kobus.internal.core.NikobusInterface] - Received: #N961626
2018-12-08 00:44:19.379 [TRACE] [kobus.internal.core.NikobusInterface] - Received: #N961626
2018-12-08 00:44:19.425 [TRACE] [kobus.internal.core.NikobusInterface] - Received: #
2018-12-08 00:44:19.449 [TRACE] [kobus.internal.core.NikobusInterface] - Received: N961626
2018-12-08 00:44:19.535 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#N961626, repeats=3]
2018-12-08 00:44:19.539 [TRACE] [ding.nikobus.internal.NikobusBinding] - Sending command with ack $101266444853D1
2018-12-08 00:44:19.539 [TRACE] [nding.nikobus.internal.config.Button] - Processing command #N961626
2018-12-08 00:44:19.542 [TRACE] [s.internal.core.NikobusCommandSender] - Sending command $101266444853D1
2018-12-08 00:44:19.544 [TRACE] [ding.nikobus.internal.NikobusBinding] - Sending status update to PB_GF_Keuken_LB : ON
2018-12-08 00:44:19.545 [DEBUG] [kobus.internal.core.NikobusInterface] - Sending : $101266444853D1
2018-12-08 00:44:19.572 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $0
2018-12-08 00:44:19.597 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 512
2018-12-08 00:44:19.597 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$0512, repeats=1]
2018-12-08 00:44:19.603 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $0512
2018-12-08 00:44:20.109 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $1C66
2018-12-08 00:44:20.134 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 4400FF00000000F
2018-12-08 00:44:20.158 [TRACE] [kobus.internal.core.NikobusInterface] - Received: F092D96
2018-12-08 00:44:20.158 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$1C664400FF00000000FF092D96, repeats=1]
2018-12-08 00:44:20.163 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $1C664400FF00000000FF092D96
2018-12-08 00:44:20.166 [TRACE] [obus.internal.core.NikobusAckMonitor] - Received expected ack '$1C664400FF00000000FF092D96'
```

**Comment by 9037568** [comment]
This log does not contain the error you originally posted. Has it gone away?

**Comment by bloodybeet** [comment]
Just wanted to chime in saying everybody with the Nikobus binding has this
issue. This has been occurring since the migration to 2.0 and there are
several threads about it.

The original contributor has since stopped supporting this binding. I have
checked out the code, but haven't got myself to dedicate the time to setup
a test environment etc, it's a bit overwhelming just to do some minor
bugfixing. But until one of us dives into the code, this is an open issue.

**Comment by janssen-bart** [comment]
Sorry I already  posted in the community but no help from there.

Here some logs about status update:
```
018-12-10 20:38:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 021E
2018-12-10 20:43:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1522
2018-12-10 20:48:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1022
2018-12-10 20:53:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 6644
2018-12-10 20:58:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 6644
2018-12-10 21:03:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for C07E
2018-12-10 21:08:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 021E
2018-12-10 21:13:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1522
2018-12-10 21:18:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1022
2018-12-10 21:23:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 6644
2018-12-10 21:28:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 6644
2018-12-12 07:08:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 021E
2018-12-12 07:13:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1522
2018-12-12 07:18:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1022
2018-12-12 07:18:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 1022
```
```

==> /var/log/openhab2/openhab.log <==
2018-12-12 07:28:57.438 [TRACE] [ding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 6644
2018-12-12 07:28:57.442 [TRACE] [ding.nikobus.internal.NikobusBinding] - Sending command with ack $10176644A3A3BE
2018-12-12 07:28:57.450 [TRACE] [s.internal.core.NikobusCommandSender] - Sending command $10176644A3A3BE
2018-12-12 07:28:57.454 [DEBUG] [kobus.internal.core.NikobusInterface] - Sending : $10176644A3A3BE
2018-12-12 07:28:57.479 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $
2018-12-12 07:28:57.503 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$0517, repeats=1]
2018-12-12 07:28:57.503 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 0517
2018-12-12 07:28:57.506 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $0517
2018-12-12 07:28:57.687 [TRACE] [kobus.internal.core.NikobusInterface] - Received: $1C66440000
2018-12-12 07:28:57.711 [TRACE] [kobus.internal.core.NikobusInterface] - Received: 00FF00000008C17
2018-12-12 07:28:57.736 [DEBUG] [internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$1C6644000000FF00000008C17E, repeats=1]
2018-12-12 07:28:57.736 [TRACE] [kobus.internal.core.NikobusInterface] - Received: E
2018-12-12 07:28:57.739 [TRACE] [obus.internal.core.NikobusAckMonitor] - Processing nikobus command $1C6644000000FF00000008C17E
2018-12-12 07:28:57.750 [TRACE] [obus.internal.core.NikobusAckMonitor] - Received expected ack '$1C6644000000FF00000008C17E'
```

**Comment by DaanDW** [comment]
@Bart, does this means that when I change to another Java that my problem is solved?
whit my upgrade from Openhab 1.x to 2.x I also change from ORACLE java to ZULU java.

For the trace logs? do I need to change "userdata/etc/org.ops4j.pax.logging.cfg"?
Could somebody help me with this? The info in the link to the forum is not very clear for me (I'm not an software engineer :) )

thanks!

**Comment by 9037568** [comment]
>For the trace logs? do I need to change "userdata/etc/org.ops4j.pax.logging.cfg"?

See Rich's excellent [tutorial on openHAB logging](https://community.openhab.org/t/taming-openhab-2-logging/13976).

**Comment by DaanDW** [comment]
> Sorry I already posted in the community but no help from there.
> [...] I don't want to steal the tread [...]

@janssen-bart could you share the way how you create the nikobus trace logger?
I can't get it to work, even worse al my loggings are stopped.

**Comment by DaanDW** [comment]
> The next step is to provide the TRACE logs. See [this community forum topic](https://community.openhab.org/t/taming-openhab-2-logging/13976) if you need help setting logging up.

Finnaly it seems I have succeeded to start the trace log.

This is a part where it goes wrong:

`15-Dec-2018 11:57:55.913 [TRACE] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Requesting scheduled status update for 0657
15-Dec-2018 11:57:55.917 [TRACE] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Sending command with ack $10120657612BC9
15-Dec-2018 11:57:55.921 [TRACE] [binding.nikobus.internal.core.NikobusCommandSender] - Sending command $10120657612BC9
15-Dec-2018 11:57:55.924 [DEBUG] [hab.binding.nikobus.internal.core.NikobusInterface] - Sending : $10120657612BC9
15-Dec-2018 11:57:55.947 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: $
15-Dec-2018 11:57:55.971 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 0512
15-Dec-2018 11:57:55.973 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$0512, repeats=1]
15-Dec-2018 11:57:55.978 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command $0512
15-Dec-2018 11:57:56.215 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #
15-Dec-2018 11:57:56.236 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: NF80087
15-Dec-2018 11:57:56.258 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #
15-Dec-2018 11:57:56.279 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: NF80087
15-Dec-2018 11:57:56.364 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#NF80087, repeats=2]
15-Dec-2018 11:57:56.367 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command #NF80087
15-Dec-2018 11:57:57.921 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - No ack received within poll time (2000).
15-Dec-2018 11:57:57.924 [ERROR] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Error occurred during scheduled status refresh.
java.util.concurrent.TimeoutException: No ACK received within timeout and retry count.
	at org.openhab.binding.nikobus.internal.core.NikobusAckMonitor.waitForAck(NikobusAckMonitor.java:92) [267:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding.sendCommand(NikobusBinding.java:155) [267:org.openhab.binding.nikobus:1.12.0]
	at org.openhab.binding.nikobus.internal.NikobusBinding$2.run(NikobusBinding.java:288) [267:org.openhab.binding.nikobus:1.12.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
`

sometimes the message about **no ack received within poll time (2000)** is in the log without a error:

`15-Dec-2018 13:46:35.256 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #N
15-Dec-2018 13:46:35.277 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: DAC422
15-Dec-2018 13:46:35.299 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #NDA
15-Dec-2018 13:46:35.320 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: C422
15-Dec-2018 13:46:35.405 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#NDAC422, repeats=2]
15-Dec-2018 13:46:35.407 [TRACE] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Sending command with ack $1017702646925B
15-Dec-2018 13:46:35.407 [TRACE] [org.openhab.binding.nikobus.internal.config.Button] - Processing command #NDAC422
15-Dec-2018 13:46:35.408 [TRACE] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Sending status update to Waskot_bottom_left : ON
15-Dec-2018 13:46:35.408 [TRACE] [binding.nikobus.internal.core.NikobusCommandSender] - Sending command $1017702646925B
15-Dec-2018 13:46:35.409 [DEBUG] [hab.binding.nikobus.internal.core.NikobusInterface] - Sending : $1017702646925B
15-Dec-2018 13:46:35.431 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: $0
15-Dec-2018 13:46:35.453 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=$0517, repeats=1]
15-Dec-2018 13:46:35.453 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 517
15-Dec-2018 13:46:35.454 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command $0517
15-Dec-2018 13:46:35.614 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #N
15-Dec-2018 13:46:35.636 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 5AC422
15-Dec-2018 13:46:35.658 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #N5A
15-Dec-2018 13:46:35.679 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: C422
15-Dec-2018 13:46:35.764 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#N5AC422, repeats=2]
15-Dec-2018 13:46:35.765 [TRACE] [org.openhab.binding.nikobus.internal.config.Button] - Processing command #N5AC422
15-Dec-2018 13:46:35.766 [TRACE] [rg.openhab.binding.nikobus.internal.NikobusBinding] - Sending status update to Waskot_bottom_right : ON
15-Dec-2018 13:46:35.768 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command #N5AC422
15-Dec-2018 13:46:35.977 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #
15-Dec-2018 13:46:35.999 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: NC21424
15-Dec-2018 13:46:36.022 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #NC
15-Dec-2018 13:46:36.044 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 21424
15-Dec-2018 13:46:36.114 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #
15-Dec-2018 13:46:36.136 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: NC21424
#NC21424
15-Dec-2018 13:46:36.158 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #NC21424
15-Dec-2018 13:46:36.191 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #N
15-Dec-2018 13:46:36.214 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: C21424
15-Dec-2018 13:46:36.236 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #NC2
15-Dec-2018 13:46:36.259 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 1424
15-Dec-2018 13:46:36.344 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#NC21424, repeats=7]
15-Dec-2018 13:46:36.346 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command #NC21424
15-Dec-2018 13:46:36.886 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #N
15-Dec-2018 13:46:36.908 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: F80087
15-Dec-2018 13:46:36.931 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: #NF80
15-Dec-2018 13:46:36.953 [TRACE] [hab.binding.nikobus.internal.core.NikobusInterface] - Received: 087
15-Dec-2018 13:46:37.038 [DEBUG] [nding.nikobus.internal.core.NikobusCommandReceiver] - Received NikobusCommand [command=#NF80087, repeats=2]
15-Dec-2018 13:46:37.041 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - Processing nikobus command #NF80087
15-Dec-2018 13:46:37.409 [TRACE] [ab.binding.nikobus.internal.core.NikobusAckMonitor] - No ack received within poll time (2000).
`

**Comment by DaanDW** [comment]
I collected an nikobus logfile of ± 24 hours (I include it here. Scheduled tasks are marked in yellow, poll problems are marked in red and errors are marked in brown).

[24h_nikobus_log.docx](https://github.com/openhab/openhab1-addons/files/2683726/24h_nikobus_log.docx)


Like I said before, I'm not an software engineer but I did a quick look at the log and this are my remarks:

- After the occurrence of an error, the status requests will continue to be executed.
- After the first error has occurred the received results seem to be processed but the status is no longer pushed to the items.

That is what I think of it, but I'm not sure of that is correct.

I hope someone can help the Nikobus users! this problem affects us all.

**Comment by crnjan** [comment]
There is a v2 Nikobus binding available now and should resolve this, please see https://community.openhab.org/t/nikobus-v2/80241.
