### ISSUE TITLE
[Plex] Cannot control Plex 

### ISSUE THREAD

**Issue by staehler** [openhab/openhab1-addons#5668]
Hi,
I cannot control plex although it worked already.

I get the following log:
```
2018-09-22 20:29:52.094 [WARN ] [org.apache.karaf.services.eventadmin] - EventAdmin: Exception during event dispatch [org.osgi.service.event.Event [topic=openhab/command/PlexWZPause] {item=PlexWZPause, bridgemarker=true, command=ON, timestamp=1537640992046} | {org.osgi.service.event.EventHandler}={port=32400, service.id=461, service.bundleid=244, service.scope=bundle, refresh=5000, component.name=org.openhab.binding.plex.binding, component.id=291, token=xxxxxxxxxx, host=192.168.x.y, event.topics=openhab/command/*, service.pid=org.openhab.plex} | Bundle(org.openhab.binding.plex_1.13.0.201809190110 [244])]
java.lang.NullPointerException: null
        at org.openhab.binding.plex.internal.PlexConnector.getHost(PlexConnector.java:417) ~[?:?]
        at org.openhab.binding.plex.internal.PlexConnector.sendCommand(PlexConnector.java:238) ~[?:?]
        at org.openhab.binding.plex.internal.PlexBinding.internalReceiveCommand(PlexBinding.java:147) ~[?:?]
        at org.openhab.core.binding.AbstractBinding.receiveCommand(AbstractBinding.java:94) ~[?:?]
        at org.openhab.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:45) ~[?:?]
        at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:415) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutBlacklistTiming(HandlerTask.java:82) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:104) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at org.apache.felix.eventadmin.impl.tasks.AsyncDeliverTasks$TaskExecuter.run(AsyncDeliverTasks.java:166) [3:org.apache.karaf.services.eventadmin:4.2.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```
Has anybody an idea, what this means?

I'm running 
openhab2 2.4.0~20180919034315-1 on debian
Plex Media Server 1.13.5.5332-21ab172de on QNAP
Plex Home Theater 1.8.0.148-573b6d73 on MacMini.

Which information do you need for further investigation? Thanks in advance.

**Comment by 9037568** [comment]
As always, you should really attach a debug log if you want to try to get to the root cause.

However, [here is a jar](https://drive.google.com/open?id=1uSQef7JUxIB1V-RaHmx_bKnCwiwG8WIK) which should eliminate this Null Pointer Exception.

And [here's the code change](https://github.com/openhab/openhab1-addons/compare/master...9037568:plex?expand=1) for this.

**Comment by staehler** [comment]
Hi Chris,
thanks for your reply and sorry for the delay. I attached my debug log now. Hope you can see something - I'm no developer ...
[test.log](https://github.com/openhab/openhab1-addons/files/2412426/test.log)

**Comment by staehler** [comment]
Thanks for looking. Than it must be a bug, as my openhab server can _ping_, _nslookup_ and _telnet plex 32400_ my plex server. 
The plex binding worked long time for me absolutely reliable, so there must have been introduced a bug with the last updates. Unfortunately I cannot say, which upgrade was responisble for it.

This post is already labeled as bug. Do I have to do any further thing or is this registered for debugging now?

**Comment by 9037568** [comment]
If you're issuing a ping to `plex`, that's not the right value.

The question is, what do you get when you ping this specific address?

`192-168-2-1.cf073ad3381244a6b493a4cc8501b98e.plex.direct`

If that succeeds on the OH device, then this is a network issue and we'll need input from OH2/ESH.
Especially if you can verify this same setup works correctly on an earlier version of OH2 like 2.3, etc.

**Comment by staehler** [comment]
With your hint I could resolve my problem, thanks a lot.
This hostname was not pingable or resolvable, then I found this [comment](https://community.openhab.org/t/what-have-you-done-with-your-plex-binding/5846/11). 
That's what I had to do in my fritzbox (for them who might see the same problem):
Add to
Heimnetz -> Netzwerk -> Netzwerkeinstellungen -> DNS-Rebind-Schutz
*.plex.direct

Voila, it works :-)
