### ISSUE TITLE
[CalDAV] Binding not working with OH2 on Docker Image

### ISSUE THREAD

**Issue by PSTobiasMueller** [openhab/openhab1-addons#5677]
## Expected Behavior
The Caldav Binding should connect to my iCloud Calender

## Current Config:
caldavio.cfg
```
caldavio:arbeit:url=https://URL
caldavio:arbeit:username=XXXXXX
caldavio:arbeit:password=XXXXXX
caldavio:arbeit:reloadInterval=30
caldavio:arbeit:preloadTime=60
caldavio:arbeit:disableCertificateVerification=true
caldavio:arbeit:charset="UTF-8"
```

## Current Behavior
The Problem is that i the binding isn't loading. In the config File always get the following error:
```
2018-10-08 16:33:02.332 [WARN ] [.io.caldav.internal.CalDavLoaderImpl] - Unable to parse configuration parameter: charset
2018-10-08 16:33:02.340 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.openhab.io.caldav.CalDavLoader, id=1825, bundle=235/mvn:org.openhab.io/org.openhab.io.caldav/1.12.0]: Updating property CalDAV IO of configuration org.openhab.caldavio caused a problem: Unable to parse configuration parameter: charset
org.osgi.service.cm.ConfigurationException: CalDAV IO : Unable to parse configuration parameter: charset
	at org.openhab.io.caldav.internal.CalDavLoaderImpl.updated(CalDavLoaderImpl.java:183) [235:org.openhab.io.caldav:1.12.0]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) [8:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [8:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [8:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1792) [8:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141) [8:org.apache.felix.configadmin:1.8.16]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109) [8:org.apache.felix.configadmin:1.8.16]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

The Problem is the shadowed config file caldavio.config in "openhab\userdata\config\org\openhab"
My config file only has the lines i showed in the config i showed above. Even tough the caldavia.config always gets the following additional entry:
`charset="UTF-8"`
I've already deleted the config file. But every time openhab regenerates the file it adds the charset line.

Problem is that the line should be like the one in my config.

## Steps to Reproduce (for bugs)
1. Setup Docker Openhab Image
2. Install CalDav Binding
3. Create CFG File

## Context
I need the CalDav to get Events from my iCloud Calender

## Your Environment
My OpenHab is running as a Docker Image 2.3.0:Latest on a QNAP NAS.
All other Bindings are running fine.

**Comment by 9037568** [comment]
I think the config line for charset should be:

````
caldavio:arbeit:charset=UTF-8
````

I recommend stopping the binding, clearing the cache and then making this config change. Then restart the binding.

**Comment by 9037568** [comment]
And you're still seeing the error message?

I haven't been able to reproduce this so far.  I set up a config and did not see any warnings, but I'm not using Docker.  I wouldn't expect Docker to make a difference, though.

If you can provide a debug log, that would be helpful.

**Comment by PSTobiasMueller** [comment]
Yep. Error Still exists. I'll try to uninstall the binding, Restart the OpenHab Container and try the CalDavIO Config/Installation from scratch again.

**Comment by MrksHfmn** [comment]
The issue still exists after a fresh install of CalDAV Binding (personal) (all configs are empty):

```
2020-08-16 15:09:55.935 [WARN ] [.io.caldav.internal.CalDavLoaderImpl] - Unable to parse configuration parameter: charset
2020-08-16 15:09:55.941 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.openhab.io.caldav.CalDavLoader, id=409, bundle=263/mvn:org.openhab.io/org.openhab.io.caldav/[1.14.0,1.15)]: Updating property CalDAV IO of configuration org.openhab.caldavio caused a problem: Unable to parse configuration parameter: charset
org.osgi.service.cm.ConfigurationException: CalDAV IO : Unable to parse configuration parameter: charset
        at org.openhab.io.caldav.internal.CalDavLoaderImpl.updated(CalDavLoaderImpl.java:187) ~[?:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[bundleFile:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [bundleFile:?]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [bundleFile:?]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1118) [bundleFile:?]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1074) [bundleFile:?]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [bundleFile:?]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [bundleFile:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by 9037568** [comment]
No further development can be done in OH1.
