### ISSUE TITLE
[FritzBoxTr064] soap error

### ISSUE THREAD

**Issue by edgarjung** [openhab/openhab1-addons#5746]
## Expected Behavior

No SOAP Error. Binding thru paperUI

## Current Behavior

Throws SOAP Error on TR-064. Things cannot be added thru paperUI

018-12-28 19:27:12.614 [ERROR] [org.openhab.binding.fritzboxtr064   ] - bundle org.openhab.binding.fritzboxtr064:1.13.0 (285)[org.openhab.binding.fritzboxtr064.binding(26)] : The activate method has thrown an exception
java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
	at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.activate(FritzboxTr064Binding.java:149) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[39:org.apache.felix.scr:2.1.2]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[39:org.apache.felix.scr:2.1.2]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[39:org.apache.felix.scr:2.1.2]

Worked find on Windows 10 with jdk 8.x and openhab 2.3

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

openHAB 2.4.0 Release Build

**Comment by 9037568** [comment]
>openjdk version "10.0.2" 2018-07-17

Reverting to Java 8 should fix this.
The soap classes [were moved](https://stackoverflow.com/questions/48626824/java-lang-noclassdeffounderror-javax-xml-soap-soapexception) in Java 9.

**Comment by edgarjung** [comment]
Going back to Java 8 fixed it. thanks
