### ISSUE TITLE
[bticino] binding installation fails on an NPE

### ISSUE THREAD

**Issue by dev-mansonthomas** [openhab/openhab1-addons#5752]
## Expected Behavior
Install openhab 2.4.0 stable, install BTICINO binding, click inbox, click the + button and find the BTICINO binding

## Current Behavior

Install openhab 2.4.0 stable, install BTICINO binding, click inbox, click the + button, and I can't find the BTICINO binding.

when checking the openhab.log, I can see the following NPE : 

```
2019-01-03 23:20:50.546 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2019-01-03 23:20:53.627 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=369, bundle=222/mvn:org.openhab.binding/org.openhab.binding.bticino/1.13.0]: Unexpected problem updating configuration org.openhab.bticino
java.lang.NullPointerException: null
	at org.openhab.binding.bticino.internal.BticinoBinding.updated(BticinoBinding.java:195) ~[?:?]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1102) [9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1058) [9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [9:org.apache.felix.configadmin:1.9.4]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [9:org.apache.felix.configadmin:1.9.4]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-01-03 23:22:51.594 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'hue:bridge:001788a505b6' to inbox.
```

I also have a lot of exception like this : 

```
2019-01-03 23:19:53.641 [ERROR] [ore.common.registry.AbstractRegistry] - Cannot inform the listener "org.openhab.core.items.internal.ItemUIRegistryDelegate@767f73c" about the "REMOVED" event: org/openhab/core/compat1x/internal/ItemMapper
java.lang.NoClassDefFoundError: org/openhab/core/compat1x/internal/ItemMapper
    at org.openhab.core.items.internal.ItemUIRegistryDelegate.removed(ItemUIRegistryDelegate.java:124) ~[?:?]
    at org.openhab.core.items.internal.ItemUIRegistryDelegate.removed(ItemUIRegistryDelegate.java:1) ~[?:?]
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:346) ~[?:?]

... skipped part
```

## Context
New installation, want to connect my F454 web server from BTICION with openhab

## Your Environment
openhab 2.4.0, docker image, runing on Synology DS1813+ with docker package.
installed with the following command : 
```
docker run \
        --name openhab \
        --net=host \
        --tty \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v /volume1/docker/openhab/addons:/openhab/addons \
        -v /volume1/docker/openhab/conf:/openhab/conf \
        -v /volume1/docker/openhab/userdata:/openhab/userdata \
        -d \
        --restart=always \
		-e "EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Paris" \
        openhab/openhab:2.4.0
```

I'm connected remotely to my Synology Nas, using ssh tunnels to access the web UI.
I've managed to have the pioneer AV Binding working, and the Philips Hue (although configuration not finished, I need to press the button to get the generated username).

**Comment by 9037568** [comment]
Please add your bticino.cfg file and item definitions.

**Comment by 9037568** [comment]
That's what I'd recommend.
