### ISSUE TITLE
[FritzBoxTR064]: FritzBox 6591 cannot be reached, log shows errors

### ISSUE THREAD

**Issue by Ageraluon** [openhab/openhab1-addons#5879]
I've initially installed a FB7390, using the settings suggested and a dedicated user account on the FB worked well. 
When my new FB6591 arrived, I cloned the settings to the new device, which can be reached under the same IP. Settings were not changed.

## Current Behavior
The installed items show no data, the log shows the following message on every call:

```
java.lang.NullPointerException: null
	at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.execute(FritzboxTr064Binding.java:219) ~[?:?]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) ~[225:org.openhab.core.compat1x:2.4.0]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [225:org.openhab.core.compat1x:2.4.0]
2019-07-18 22:43:34.858 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - No tr064 service found for service id urn:LanDeviceHosts-com:serviceId:Hosts1
2019-07-18 22:43:34.858 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - Error constructing request SOAP msg for getting parameter. null
2019-07-18 22:43:34.859 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - Could not determine data to be sent to FritzBox!
2019-07-18 22:43:34.859 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread FritzboxTr064 Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.execute(FritzboxTr064Binding.java:219) ~[?:?]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) ~[225:org.openhab.core.compat1x:2.4.0]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [225:org.openhab.core.compat1x:2.4.0]
2019-07-18 22:43:35.887 [INFO ] [messageLogger                       ] - C->B PINGREQ <milight-hub-3929577>
2019-07-18 22:43:35.887 [INFO ] [messageLogger                       ] - C<-B PINGRESP <milight-hub-3929577>
2019-07-18 22:43:39.861 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - No tr064 service found for service id urn:LanDeviceHosts-com:serviceId:Hosts1
2019-07-18 22:43:39.863 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - Error constructing request SOAP msg for getting parameter. null
2019-07-18 22:43:39.864 [WARN ] [ing.fritzboxtr064.internal.Tr064Comm] - Could not determine data to be sent to FritzBox!
2019-07-18 22:43:39.864 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread FritzboxTr064 Refresh Service
java.lang.NullPointerException: null
	at org.openhab.binding.fritzboxtr064.internal.FritzboxTr064Binding.execute(FritzboxTr064Binding.java:219) ~[?:?]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) ~[225:org.openhab.core.compat1x:2.4.0]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [225:org.openhab.core.compat1x:2.4.0]
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

openhab 2.4.0 running in a docker container on a windows host.

**Comment by 9037568** [comment]
You should try clearing the cache first.
If the problem persists, please add the logs and configs you were asked to provide.
