### ISSUE TITLE
Error when creating a skeleton for a new binding

### ISSUE THREAD

**Issue by matthias79** [openhab/openhab1-addons#628]
Hi, 

when creating a skeleton for a new binding I got the following error:

C:\Users\rosch\Documents\GitHub\openhab\bundles\binding>mvn archetype:generate -
B -DarchetypeGroupId=org.openhab.archetype -DarchetypeArtifactId=org.openhab.arc
hetype.binding -DarchetypeVersion=1.4.0-SNAPSHOT -Dauthor=Matthias Schneider -Dv
ersion=1.4.0 -DartifactId=org.openhab.binding.blukii -Dpackage=org.openhab.bindi
ng.blukii -Dbinding-name=blukii
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target pla
tform specification artifact org.openhab:targetplatform:target:openhab:1.4.0-SNA
PSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeExcept
ion: Could not resolve target platform specification artifact org.openhab:target
platform:target:openhab:1.4.0-SNAPSHOT
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:164)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specifi
cation artifact org.openhab:targetplatform:target:openhab:1.4.0-SNAPSHOT
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationRea
der.addTargetArtifact(DefaultTargetPlatformConfigurationReader.java:334)
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationRea
der.setTarget(DefaultTargetPlatformConfigurationReader.java:288)
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationRea
der.getTargetPlatformConfiguration(DefaultTargetPlatformConfigurationReader.java
:71)
        at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupP
roject(DefaultTychoDependencyResolver.java:78)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProj
ectsRead(TychoMavenLifecycleParticipant.java:77)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:271)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorE
xception
C:\Users\rosch\Documents\GitHub\openhab\bundles\binding>

Is there anybody else having this issue ?

Thanks,
Matthias

**Comment by dani6292** [comment]
I have the same problem that matthias. What could I do?
